# -*- coding: utf-8 -*-
# BBC + AJ + Politico 1008
ITEMS = [
 dict(f='bbc', q="France halts use of stun grenades after boy's hand blown off", d='2026-10-07', c='地区局势', p=78,
  zh="法国暂停在学潮中使用震撼弹",
  en="France halts use of stun grenades after boy's hand blown off in student protests",
  s="在一名高中生在抗议中被震撼弹炸断手掌后，法国警方宣布暂停在学潮处置中使用该类武器。全法多地连日爆发大规模学生与工会抗议，要求增加教育经费并撤回改革措施。内政部长否认警方存在过度暴力，但事件已引发对执法手段的广泛争议。"),
 dict(f='bbc', q="Canada suspends plans to expand assisted dying", d='2026-10-07', c='其他', p=76,
  zh="加拿大暂停将安乐死扩大至精神疾病患者",
  en="Canada suspends plans to expand assisted dying to people with mental illness",
  s="加拿大政府宣布无限期暂停将医疗辅助死亡（安乐死）的适用范围扩大至仅有精神疾病的患者，称需要更多时间评估保障措施。该议题在加拿大社会争议极大，反对者担心弱势群体被变相推向死亡。原计划扩大适用本应于今年生效，现被推迟。"),
 dict(f='bbc', q="Chemistry Nobel awarded for solving mystery of life's asymmetry", d='2026-10-07', c='AI·科技', p=76,
  zh="化学诺奖授予破解生命「手性」之谜的科学家",
  en="Chemistry Nobel awarded for solving mystery of life's asymmetry",
  s="瑞典皇家科学院将2026年诺贝尔化学奖授予两名科学家，以表彰他们在不对称催化领域的开创性贡献，其成果破解了生命分子手性起源的难题并推动了现代药物合成。相关技术使多种手性药物的工业化生产成为可能。此前一天，物理学奖授予了南极中微子天文台「冰立方」项目的负责人。"),
 dict(f='aj', q="Yemeni government forces claim 1,860 Houthis", d='2026-10-08', c='地区局势', p=80,
  zh="也门政府军称已「清除」1860名胡塞武装人员",
  en="Yemeni government forces claim 1,860 Houthis 'neutralised'",
  s="也门政府军宣布在近期军事行动中「清除」1860名胡塞武装人员，并称已控制西南部若干战略高地。胡塞武装则持续对沙特境内机场与也门政府控制区发动导弹和无人机袭击。双方战报均难以独立核实，也门战事的升级正加剧地区人道危机与航运风险。"),
 dict(f='aj', q="US stocks slide as oil prices fluctuate over renewed Iran war fears", d='2026-10-08', c='地区局势', p=82,
  zh="伊朗战争担忧重燃 美股下挫油价震荡",
  en="US stocks slide as oil prices fluctuate over renewed Iran war fears",
  s="受伊朗战事再度升级与霍尔木兹海峡油轮遇袭影响，美国股市下挫，国际油价剧烈震荡。市场担忧能源供应中断推高通胀，并迫使美联储维持紧缩立场。分析人士指出，债市收益率高企与AI资本开支融资需求叠加，正加大全球资产价格的波动风险。"),
 dict(f='aj', q="Saudi Arabia confirms three dead in Houthi strikes on its airports", d='2026-10-08', c='地区局势', p=84,
  zh="沙特确认胡塞武装袭击机场致3人死亡",
  en="Saudi Arabia confirms three dead in Houthi strikes on its airports",
  s="沙特阿拉伯确认胡塞武装对本国机场的袭击造成3人死亡，并称防空系统拦截了多枚来袭导弹与无人机。袭击导致部分航班中断，沙特随后加强对也门境内目标的打击。分析认为，也门战事的升级与美伊紧张关系相互叠加，正在推高海湾地区的安全风险。"),
 dict(f='aj', q="Russia dismisses reports of second plague case", d='2026-10-08', c='地区局势', p=78,
  zh="俄方否认出现第二例瘟疫病例",
  en="Russia dismisses reports of second plague case as 'false information'",
  s="俄罗斯当局否认有关西伯利亚实验室出现第二例肺鼠疫病例的报道，称其为「虚假信息」。此前一名实验室工作人员因不明原因肺炎死亡，世界卫生组织要求俄方提供更多细节。美方表示正密切关注，特朗普称将与普京通话。事件凸显生物实验室安全与信息透明度问题。"),
]
