# -*- coding: utf-8 -*-
# CNN / AP / WSJ / 官方源（URL 硬编码，已逐条核验）
ITEMS = [
 dict(f='hard', u='https://edition.cnn.com/2026/10/07/middleeast/houthis-attack-saudi-airports-latam-intl', s_='CNN', d='2026-10-07', c='地区局势', p=84,
  zh="伊朗支持的胡塞武装袭击沙特机场 也门冲突外溢加剧",
  en="Deadly attacks by Iran-backed Houthis on Saudi airports highlight widening fallout from Yemen conflict",
  s="胡塞武装对沙特多个机场发动致命袭击，凸显也门冲突外溢效应正在扩大。沙特方面称防空系统拦截了部分来袭武器，袭击导致航班中断与人员伤亡。分析指出，也门战事与美伊紧张关系相互叠加，海湾地区的航运与能源基础设施风险显著上升，国际油价随之波动。"),
 dict(f='hard', u='https://edition.cnn.com/2026/10/07/world/russia-suspected-plague-case-who-intl', s_='CNN', d='2026-10-07', c='地区局势', p=80,
  zh="俄称无疫情风险 世卫要求就实验室死亡事件提高透明度",
  en="Russia says no epidemic risk as WHO pushes for transparency on plague lab death",
  s="俄罗斯表示西伯利亚实验室工作人员疑似感染肺鼠疫死亡事件不构成疫情风险，但世界卫生组织要求俄方提供更多信息并提高透明度。美方表示正密切关注，特朗普称将与普京通话讨论。该事件引发国际社会对生物实验室安全管理与信息共享机制的关注。"),
 dict(f='hard', u='https://edition.cnn.com/2026/10/07/europe/france-high-school-protests-government-intl', s_='CNN', d='2026-10-07', c='地区局势', p=78,
  zh="法国政府称正在倾听学生诉求 抗议能否平息仍待观察",
  en="French leaders say they're listening to students. Will it be enough?",
  s="法国多地持续爆发高中生与工会抗议，要求增加教育经费并撤回改革措施。政府表示正在倾听学生诉求并承诺追加投入，但抗议组织者认为回应不足。此前一名学生在冲突中手掌被震撼弹炸断，警方已暂停使用该类武器，事件进一步激化社会情绪。"),
 dict(f='hard', u='https://edition.cnn.com/2026/10/07/europe/maricarmen-spain-eviction-crisis-dies-intl-latam', s_='CNN', d='2026-10-07', c='其他', p=74,
  zh="西班牙被驱逐老人去世 曾引发全国住房抗议",
  en="Evicted 87-year-old who became a symbol of Spain's housing crisis has died",
  s="西班牙87岁老人玛丽亚·德尔卡门·阿巴斯卡尔在医院去世，她因遭驱逐而成为西班牙住房危机的象征人物，其遭遇曾引发全国性抗议。工会与住房权益组织将其去世归因于长期居住不稳定的压力。该事件再度凸显西班牙房租与房价上涨带来的社会矛盾，政府面临更大政策压力。"),
 dict(f='hard', u='https://apnews.com/article/russia-plague-irkutsk-who-trump-c1dfff772ca769bbdf26726787432d51', s_='美联社', d='2026-10-07', c='地区局势', p=80,
  zh="世卫组织要求俄方就疑似肺鼠疫病例提供更多细节",
  en="UN health agency wants more details from Russia on suspected pneumonic plague case",
  s="世界卫生组织表示，正要求俄罗斯提供西伯利亚伊尔库茨克地区一名实验室工作人员疑似感染肺鼠疫死亡的更多细节。俄方称已按规定向世卫通报，并否认存在疫情扩散风险。美方表示密切关注，特朗普称将与普京通话。事件引发对生物安全与实验室管理的国际关注。"),
 dict(f='hard', u='https://apnews.com/article/stocks-markets-rates-oil-earnings-44b75c188756038371cf3112ede9cee8', s_='美联社', d='2026-10-07', c='其他', p=80,
  zh="全球股市回落 华尔街自纪录高位下挫",
  en="Wall Street retreats from its record as stocks fall worldwide",
  s="受债券收益率攀升与油价波动影响，全球股市普遍回落，华尔街主要指数从历史高位下挫。投资者关注美联储会议纪要释放的政策信号以及中东局势对能源供应的冲击。分析人士指出，AI相关资本开支的融资需求正与政府发债争夺资金，推高长端利率并压制估值。"),
 dict(f='hard', u='https://apnews.com/article/israel-palestinians-oct-7-war-gaza-anniversary-da70839eab71a77db31237fe79142ead', s_='美联社', d='2026-10-07', c='地区局势', p=82,
  zh="以色列纪念10·7袭击三周年 加沙民众仍在废墟中挣扎",
  en="Israelis mourn Oct. 7 attack as Palestinians in Gaza languish in ruins of the war it sparked",
  s="以色列举行活动悼念10月7日哈马斯袭击三周年，遇难者家属要求政府就当日安全失误追责。与此同时，加沙地带民众仍在战争废墟中艰难求生，人道援助严重不足，停火协议执行面临考验。纪念活动在以色列大选临近背景下带有强烈政治色彩。"),
]
