# -*- coding: utf-8 -*-
# NYT + Guardian 1008
ITEMS = [
 dict(f='nyt', q="Europe's Trade Tensions With China Are Coming to a Head", d='2026-10-08', c='中欧与盟友', p=90,
  zh="欧洲与中国的贸易紧张关系走向摊牌",
  en="Europe's Trade Tensions With China Are Coming to a Head",
  s="随着欧盟对华贸易救济措施与中方反制措施相互叠加，欧中经贸关系进入关键摊牌期。报道指出，欧盟对中国电动汽车、化工品与钢铁的贸易调查持续扩大，而中方则以反倾销调查与出口管制回应，双方在产能过剩、补贴与市场准入上的分歧难以短期弥合。欧洲产业界担忧供应链中断风险上升。"),
 dict(f='nyt', q="Rubio Urges Europe to Awaken From", d='2026-10-07', c='美国内政', p=86,
  zh="鲁比奥促欧洲从「沉睡」中醒来 维护西方主导地位",
  en="Rubio Urges Europe to Awaken From 'Slumber' and Uphold Western Dominance",
  s="美国国务卿鲁比奥在希腊发表演讲，呼吁欧洲摆脱「沉睡」状态，在防务、移民与产业政策上承担更多责任，共同维护西方主导地位。他重申特朗普政府的「美国优先」并不等于孤立主义，而是要求盟友分担成本。此番表态被视为美方在跨大西洋关系紧张背景下的一次安抚与施压并举。"),
 dict(f='nyt', q="Case of U.S. Marine Accused of Murder in Japan", d='2026-10-07', c='地区局势', p=82,
  zh="美海军陆战队员在日涉谋杀案引发日本舆论哗然",
  en="Case of U.S. Marine Accused of Murder in Japan Draws Outcry",
  s="一名驻日美海军陆战队员因涉嫌在冲绳杀害一名日本女性被捕，案件在日本引发强烈舆论反应。冲绳地方政府与民众再次要求缩减美军基地规模并修改驻军地位协定。美方已下令限制基地人员外出并禁止饮酒，以平息事态。该案给日美同盟关系带来新的政治压力。"),
 dict(f='nyt', q="How a Shadow Economy in Asia Is Keeping Iranian Oil Flowing", d='2026-10-07', c='地区局势', p=84,
  zh="亚洲影子经济如何维持伊朗石油流动",
  en="How a Shadow Economy in Asia Is Keeping Iranian Oil Flowing",
  s="调查报道揭示，一个横跨东南亚与中东的影子船队与离岸金融网络，正通过船对船转运、关闭应答器与伪造单证等方式维持伊朗石油出口，规避美方制裁。相关交易涉及马来西亚、新加坡等地的小型航运与贸易公司。美方近期已加大对相关实体的制裁力度，但执行难度依然很高。"),
 dict(f='nyt', q="3 Killed and Dozens Injured in Attacks on Saudi Airports", d='2026-10-07', c='地区局势', p=84,
  zh="沙特机场遭袭致3死数十伤 胡塞武装宣称负责",
  en="3 Killed and Dozens Injured in Attacks on Saudi Airports, as Houthis Claim Strikes",
  s="也门胡塞武装对沙特境内多个机场发动袭击，造成至少3人死亡、数十人受伤，沙特防空系统拦截了部分来袭导弹与无人机。这是近期也门战事升级以来针对沙特民用基础设施的最严重袭击之一。沙特与也门政府军随后加强了对胡塞控制区的军事行动，地区局势持续紧张。"),
 dict(f='nyt', q="Can Artificial Intelligence Learn the Art of Surgery", d='2026-10-07', c='AI·科技', p=78,
  zh="人工智能能否学会外科手术的技艺",
  en="Can Artificial Intelligence Learn the Art of Surgery?",
  s="报道探访加拿大研究团队如何训练人工智能系统学习外科手术操作，探索AI在手术规划、器械控制与技能评估中的应用。研究人员指出，手术数据稀缺、个体差异大与责任归属不清是主要障碍。文章认为AI短期内更可能作为外科医生的辅助工具，而非替代者。"),
 dict(f='guardian', q="Satellite images show attack jets at Chinese military facility in Laos", d='2026-10-07', c='地区局势', p=84,
  zh="卫星图像显示中国在老挝军事设施部署攻击机",
  en="Satellite images show attack jets at Chinese military facility in Laos",
  s="卫星图像显示，中国在老挝北部一处军事设施部署了攻击机，引发外界对该设施用途与中方在东南亚军事存在的关注。分析人士认为，该基地可能用于训练与后勤保障，但也可能提升中国在湄公河次区域的军事投射能力。老挝方面尚未就此作出公开说明。"),
]
