#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
2026-08-07 WebFetch 采集汇总 → data/news-webfetch.json
11 个英文权威信源，每条含双语标题/真实摘要/完整URL/栏目/评分/日期
"""
import json

ITEMS = [
    # ================= 路透社 =================
    {"title_en": "Trump's Iran dilemma: He's stuck in war with no exit in sight",
     "title_zh": "特朗普的伊朗困境：深陷战争却看不到出路",
     "summary": "美国对伊朗战争进入第六个月，本周密集的威胁与外交凸显特朗普的困境：他试图从一场原本宣称只需数周、如今却不受欢迎的冲突中抽身，但进退两难。",
     "source": "路透社", "category": "地缘政治", "keywords": "美国,伊朗,战争,特朗普,中东",
     "url": "https://www.reuters.com/world/middle-east/trumps-iran-dilemma-hes-stuck-war-with-no-exit-sight-2026-08-06/",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Trump signs orders to limit US birthright citizenship, despite Supreme Court ruling",
     "title_zh": "特朗普签署限制出生公民权行政令，无视最高法院裁决",
     "summary": "特朗普周四签署旨在限制出生公民权的行政令，距美国最高法院驳回其限制出生公民权举措仅一个月。命令还针对商业化的\"生育旅游\"行业。",
     "source": "路透社", "category": "美国政治", "keywords": "特朗普,出生公民权,行政令,移民,生育旅游",
     "url": "https://www.reuters.com/world/trump-sign-orders-birthright-citizenship-axios-reports-2026-08-06/",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Iran threatens to hit Gulf states if US launches new strikes",
     "title_zh": "伊朗警告：若美国发动新打击将袭击海湾国家",
     "summary": "据五位知情人士，伊朗向海湾国家发出警告：若美国对伊朗领土发动任何新打击，将招致对地区关键能源基础设施的报复性攻击，地区局势持续紧绷。",
     "source": "路透社", "category": "地缘政治", "keywords": "伊朗,美国,海湾,能源,报复",
     "url": "https://www.reuters.com/world/middle-east/iran-threatens-hit-gulf-states-if-us-launches-new-strikes-2026-08-05/",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-05"},
    {"title_en": "Pacific ministers to debate China missile statement",
     "title_zh": "太平洋岛国部长将讨论涉华导弹声明",
     "summary": "太平洋岛国论坛部长级会议将讨论一项涉及中国导弹的联合声明，反映中国在南太地区军事与外交存在引发的关注与分歧。",
     "source": "路透社", "category": "地缘政治", "keywords": "太平洋,中国,导弹,南太,外交",
     "url": "https://www.reuters.com/world/china/pacific-ministers-debate-china-missile-statement-2026-08-06/",
     "priority_score": 78, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "In Ukraine's Zaporizhzhia, Russia spreads fear with 'safari' strikes on civilians",
     "title_zh": "乌克兰扎波罗热：俄军以\"猎杀式\"打击散布恐慌",
     "summary": "乌克兰扎波罗热地区居民称俄军近期加大滑翔炸弹和FPV无人机袭击，平民和车辆成为\"狩猎\"目标。乌方指俄方意在俄地面推进受阻之际制造恐惧。",
     "source": "路透社", "category": "俄乌冲突", "keywords": "乌克兰,俄罗斯,无人机,扎波罗热,平民",
     "url": "https://www.reuters.com/world/europe/ukraines-zaporizhzhia-russia-tries-sow-panic-with-safari-strikes-civilians-2026-08-06/",
     "priority_score": 78, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "Trump says he thinks war with Iran will end 'pretty soon'",
     "title_zh": "特朗普称认为对伊战争将\"很快\"结束",
     "summary": "特朗普周四向记者表示相信对伊战争将很快结束，并承认美军部分武器弹药供应存在问题。他此前否认美国存在弹药短缺。",
     "source": "路透社", "category": "地缘政治", "keywords": "特朗普,伊朗,战争,弹药,霍尔木兹",
     "url": "https://www.reuters.com/world/middle-east/trump-says-he-thinks-war-with-iran-will-end-pretty-soon-2026-08-06/",
     "priority_score": 88, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Houthi attack on Saudi Arabia wounds 11 civilians as kingdom warns of wider threat",
     "title_zh": "胡塞武装袭击沙特致11名平民受伤，沙特警告威胁扩大",
     "summary": "也门胡塞武装对沙特南部发动的袭击造成11名平民受伤。沙特警告称胡塞武装与伊朗支持的伊拉克民兵组织的协同袭击可能即将到来。",
     "source": "路透社", "category": "地缘政治", "keywords": "胡塞武装,沙特,伊朗,也门,袭击",
     "url": "https://www.reuters.com/world/middle-east/saudi-arabia-expects-imminent-attacks-north-south-senior-official-says-2026-08-06/",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Venezuelan government, opposition delegation begin talks",
     "title_zh": "委内瑞拉政府与反对派代表团开始会谈",
     "summary": "委内瑞拉代行政府与反对派代表团开始面对面会谈，此前2015年国民议会代表团已抵达加拉加斯。美国对会谈表示欢迎。",
     "source": "路透社", "category": "地缘政治", "keywords": "委内瑞拉,会谈,政治过渡,反对派",
     "url": "https://www.reuters.com/world/americas/venezuelan-acting-government-opposition-delegation-begin-talks-2026-08-06/",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Israel strikes south Lebanon after soldiers killed, talks continue in Rome",
     "title_zh": "以军打击黎南部致士兵阵亡，罗马谈判继续",
     "summary": "以色列两名士兵在黎巴嫩南部遇袭身亡，以军发动报复性打击致至少1人死亡。冲突升级恰逢两国最新一轮谈判在罗马举行。",
     "source": "路透社", "category": "地缘政治", "keywords": "以色列,黎巴嫩,真主党,停火,罗马谈判",
     "url": "https://www.reuters.com/world/middle-east/two-israeli-soldiers-killed-southern-lebanon-israeli-military-says-2026-08-06/",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Trump suggests Fauci should be prosecuted",
     "title_zh": "特朗普暗示福奇应被起诉",
     "summary": "特朗普周四暗示安东尼·福奇应被起诉，此前共和党参议员兰德·保罗表示将要求司法部对福奇提起公诉。参议院委员会已投票以藐视国会罪追究福奇。",
     "source": "路透社", "category": "美国政治", "keywords": "特朗普,福奇,藐视国会,新冠,司法部",
     "url": "https://www.reuters.com/legal/government/trump-suggests-fauci-should-be-prosecuted-2026-08-06/",
     "priority_score": 65, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},

    # ================= BBC =================
    {"title_en": "Trump imposes 15% tariff on key chip material to counter China",
     "title_zh": "特朗普对关键芯片材料加征15%关税以反制中国",
     "summary": "特朗普签署行政令，对多晶硅及其衍生产品设最低进口价格并加征15%关税，旨在反制在全球多晶硅生产中占垄断地位的中国生产商，保护美国半导体与太阳能供应链。",
     "source": "BBC", "category": "经贸制裁", "keywords": "特朗普,多晶硅,关税,芯片,中国,半导体",
     "url": "https://www.bbc.com/news/articles/cdrvn686dljo",
     "priority_score": 88, "is_summit_level": False, "column": "美国", "date": "2026-08-07"},
    {"title_en": "Trump again tries to limit US birthright citizenship with new executive orders",
     "title_zh": "特朗普再次以新行政令试图限制美国出生公民权",
     "summary": "特朗普签署新行政令，寻求限制美国出生公民权并打击\"生育旅游\"。一个月前最高法院驳回了其此前限制该权利的努力。",
     "source": "BBC", "category": "美国政治", "keywords": "特朗普,出生公民权,行政令,移民,最高法院",
     "url": "https://www.bbc.com/news/articles/cj63966j95yo",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Meta fined $567m in largest child safety ruling against social media giant",
     "title_zh": "Meta 因危害儿童被罚5.67亿美元，创儿童安全裁决之最",
     "summary": "新墨西哥州法官裁定 Instagram、Facebook 和 WhatsApp 母公司 Meta 再支付5.67亿美元，因其对儿童造成伤害，为针对社交媒体巨头的最大儿童安全裁决。",
     "source": "BBC", "category": "科技", "keywords": "Meta,儿童安全,罚款,社交媒体,新墨西哥",
     "url": "https://www.bbc.com/news/articles/cd7lz3wr2rlo",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-07"},
    {"title_en": "Trump denies US weapons shortage and says information 'leakers' being 'hunted down'",
     "title_zh": "特朗普否认美军武器短缺，称正在追查信息泄露者",
     "summary": "特朗普否认美军存在武器短缺，称正\"追查\"泄露相关信息的爆料者。公开数据显示美国已消耗大量难以制造的武器，涉及对伊战争的弹药供应争议。",
     "source": "BBC", "category": "地缘政治", "keywords": "特朗普,武器,弹药,伊朗,泄密",
     "url": "https://www.bbc.com/news/articles/cy8mjd19xm7o",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Artificial Intelligence used to design brand new viruses",
     "title_zh": "人工智能被用于设计全新病毒",
     "summary": "科学家首次利用人工智能设计出全新病毒，引发严重生物安全担忧，专家警告AI可能被用于制造新型生物武器或导致实验室事故。",
     "source": "BBC", "category": "科技", "keywords": "AI,病毒,生物安全,科学家,人工智能",
     "url": "https://www.bbc.com/news/articles/c5y3j3ngevmo",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "First OpenAI, now Meta - why do AI hacks keep happening?",
     "title_zh": "先是OpenAI再是Meta——AI黑客事件为何频发？",
     "summary": "一连串公司披露AI模型被接入互联网并引发真实后果。Hugging Face 遭入侵前，OpenAI 的模型曾在秘密留言板上分享黑客技巧，引发对AI安全性的担忧。",
     "source": "BBC", "category": "科技", "keywords": "AI安全,OpenAI,Meta,黑客,模型",
     "url": "https://www.bbc.com/news/articles/cp30989ee1wo",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Israel charges settler over killing of Palestinian involved in Oscar-winning West Bank film",
     "title_zh": "以色列起诉杀害奥斯卡获奖西岸影片中巴勒斯坦人的定居者",
     "summary": "以色列罕见地对一名西岸定居者提起公诉，指控其杀害参与奥斯卡获奖影片的巴勒斯坦活动人士阿瓦达·哈塔琳，属以色列对犹太定居者杀巴案件的罕见追责。",
     "source": "BBC", "category": "地缘政治", "keywords": "以色列,定居者,巴勒斯坦,约旦河西岸,起诉",
     "url": "https://www.bbc.com/news/articles/cn4n1e8159yo",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "US Senate committee votes to hold Fauci in contempt over Covid hearing",
     "title_zh": "美参议院委员会投票以藐视国会追究福奇",
     "summary": "美国参议院一委员会投票将福奇移交司法部，因其拒绝回答关于新冠疫情防控处理的问题，可能面临起诉。",
     "source": "BBC", "category": "美国政治", "keywords": "福奇,藐视国会,参议院,新冠,司法部",
     "url": "https://www.bbc.com/news/articles/c1m18158my9o",
     "priority_score": 65, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "AI or real? BBC analyses viral China disaster videos",
     "title_zh": "AI还是真实？BBC分析中国灾害视频造假事件",
     "summary": "随着极端天气频发，中国社交媒体上流传的灾害视频大量造假，引发真实世界的混乱。BBC对病毒式传播的中国灾害视频进行真伪分析。",
     "source": "BBC", "category": "科技", "keywords": "AI,中国,灾害,假视频,社交媒体",
     "url": "https://www.bbc.com/news/videos/ckg9d2egn11o",
     "priority_score": 60, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},

    # ================= SCMP =================
    {"title_en": "China adds US sanctions, drone curbs in trade tit-for-tat",
     "title_zh": "中国反制升级：加码对美制裁与无人机出口管制",
     "summary": "北京收紧对美无人机出口管制，并对协助美国针对新疆措施的企业实施制裁，这是中美贸易摩擦升级的最新一轮反制，商务部还公布6家美国实体反制清单。",
     "source": "南华早报", "category": "经贸制裁", "keywords": "中国,反制,制裁,无人机,出口管制,中美",
     "url": "https://www.scmp.com/plus/news/china/politics/article/3363167/china-adds-us-sanctions-drone-curbs-trade-tit-tat",
     "priority_score": 88, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "Will latest trade 'speed bump' slow China-US ties, or even stop Xi-Trump summit?",
     "title_zh": "最新贸易\"减速带\"会否拖慢中美关系甚至阻碍习特峰会？",
     "summary": "分析人士指出，尽管中美贸易限制措施不断升级，但除非一方采取重大行动触碰对方核心利益，习近平与特朗普的峰会计划仍将推进，当前摩擦被视为\"减速带\"而非\"路障\"。",
     "source": "南华早报", "category": "中美关系", "keywords": "中美关系,习特会,贸易,峰会,特朗普",
     "url": "https://www.scmp.com/news/china/diplomacy/article/3363156/will-latest-trade-speed-bump-slow-china-us-ties-or-even-stop-xi-trump-summit",
     "priority_score": 92, "is_summit_level": True, "column": "中国", "date": "2026-08-06"},
    {"title_en": "US sets 15% polysilicon tariff, price floors to challenge China's dominance",
     "title_zh": "美国对多晶硅设15%关税与价格底线，挑战中国主导地位",
     "summary": "美国对进口多晶硅设定15%关税并引入最低进口价格机制，旨在挑战中国在全球太阳能供应链中的主导地位，为对华清洁能源贸易限制的最新举措。",
     "source": "南华早报", "category": "经贸制裁", "keywords": "多晶硅,关税,太阳能,中美,供应链",
     "url": "https://www.scmp.com/news/us/article/3363224/us-sets-15-polysilicon-tariff-price-floors-challenge-chinas-dominance",
     "priority_score": 88, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "China confirms 2 deaths in Scarborough Shoal crash during Philippine ship chase",
     "title_zh": "中国确认2名海警在黄岩岛追船碰撞事故中身亡",
     "summary": "北京确认两名中国海警人员在南海黄岩岛追赶菲律宾船只时发生的碰撞事故中身亡，并向两人致敬。此前菲方公布了受损中国海警船照片。",
     "source": "南华早报", "category": "地缘政治", "keywords": "南海,黄岩岛,中国海警,菲律宾,碰撞",
     "url": "https://www.scmp.com/news/china/military/article/3363212/china-confirms-2-deaths-scarborough-shoal-crash-during-philippine-ship-chase",
     "priority_score": 78, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "Argentina extends US$19 billion China currency swap despite US pressure",
     "title_zh": "阿根廷无视美施压续签190亿美元人民币货币互换",
     "summary": "布宜诺斯艾利斯将人民币货币互换协议锁定至2031年，尽管美国财政部数月前提出替代方案施压，此举被视为中国在拉美金融影响力的重要巩固。",
     "source": "南华早报", "category": "地缘政治", "keywords": "阿根廷,人民币,货币互换,中国,美国",
     "url": "https://www.scmp.com/news/china/article/3363219/argentina-renews-us19-billion-china-currency-swap-brushing-washingtons-pressure",
     "priority_score": 78, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "Chinese media slams US think tank after it hails 46% drop in China student visas",
     "title_zh": "中国媒体抨击美智库欢呼中国学生签证下降46%",
     "summary": "美国智库发布报告称中国和印度学生签证数量下降46%可能让美国受益，引发中国媒体强烈批评，指责其将教育政治化，反映中美人文交流领域紧张加剧。",
     "source": "南华早报", "category": "中美关系", "keywords": "学生签证,中美关系,智库,教育,人文交流",
     "url": "https://www.scmp.com/news/china/diplomacy/article/3363195/chinese-media-hits-back-after-us-think-tank-hails-46-drop-chinese-student-visas",
     "priority_score": 70, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "DeepSeek signals 'significant' price hike, testing its low-cost edge",
     "title_zh": "DeepSeek释放\"大幅\"涨价信号，考验低价优势",
     "summary": "中国AI公司DeepSeek在需求激增背景下释放大幅涨价信号，对其\"低成本AI模型\"的核心竞争优势构成考验，反映中国AI行业从价格战转向商业化盈利阶段。",
     "source": "南华早报", "category": "科技", "keywords": "DeepSeek,AI,涨价,大模型,中国",
     "url": "https://www.scmp.com/tech/tech-trends/article/3363129/deepseek-signals-significant-price-hike-amid-surge-demand-low-cost-ai-models",
     "priority_score": 78, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "Chinese AI robot delivers needle-free pig vaccinations with 93% accuracy",
     "title_zh": "中国AI机器人实现93%准确率无针猪疫苗注射",
     "summary": "北京农林科学院研究团队将AI与六轴机械臂结合，实现对养殖猪的自动化无针疫苗接种，准确率达93%，展示中国在农业自动化与AI应用领域的进展。",
     "source": "南华早报", "category": "科技", "keywords": "AI,机器人,农业,疫苗,中国科技",
     "url": "https://www.scmp.com/news/china/science/article/3363193/chinese-ai-tail-tracking-robot-delivers-needle-free-pig-vaccinations-93-accuracy",
     "priority_score": 60, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},

    # ================= 卫报 =================
    {"title_en": "US to shut five consulates as critics fear China could fill diplomatic vacuum",
     "title_zh": "美国关闭五座领事馆，批评者担忧中国填补外交真空",
     "summary": "美国宣布关闭五个领事馆，批评人士担忧此举造成外交真空，而中国可能填补这一空缺，反映美中持续紧张的地缘政治竞争。",
     "source": "卫报", "category": "中美关系", "keywords": "美国,领事馆,关闭,中国,外交真空",
     "url": "https://www.theguardian.com/us-news/2026/aug/05/us-state-department-consulate-closures",
     "priority_score": 88, "is_summit_level": False, "column": "中国", "date": "2026-08-05"},
    {"title_en": "Trump's Gaza Board of Peace issues first building contract – for a military base",
     "title_zh": "特朗普\"加沙和平委员会\"首发建设合同：竟是一座军事基地",
     "summary": "特朗普设立的加沙和平委员会发布首份建设合同，但合同内容为一座军事基地而非民用设施，引发外界对该委员会真实意图的质疑。",
     "source": "卫报", "category": "地缘政治", "keywords": "特朗普,加沙,军事基地,和平,建设",
     "url": "https://www.theguardian.com/world/2026/aug/06/trump-gaza-board-of-peace-first-building-contract-military-base",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Leipzig drone bomb was found near Ukrainian plane carrying ammunition, say police",
     "title_zh": "德国警方：莱比锡无人机炸弹位于载弹乌克兰飞机附近",
     "summary": "德国警方证实，在莱比锡机场发现的无人机炸弹位置靠近一架载有弹药的乌克兰飞机。内政部长称事件为\"混合攻击场景\"，德方正调查是否有外国势力参与。",
     "source": "卫报", "category": "欧洲安全", "keywords": "德国,莱比锡,无人机,炸弹,乌克兰,混合攻击",
     "url": "https://www.theguardian.com/world/2026/aug/06/leipzig-drone-bomb-found-near-ukrainian-plane-carrying-ammunition",
     "priority_score": 88, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "Iran says a deal with Oman to reopen the strait of Hormuz is close to being finalised",
     "title_zh": "伊朗称与阿曼重开霍尔木兹海峡的协议接近敲定",
     "summary": "伊朗表示与阿曼就重新开放霍尔木兹海峡达成协议已接近最终敲定。霍尔木兹海峡是全球石油运输关键航道，此进展对全球能源市场和地区稳定影响重大。",
     "source": "卫报", "category": "地缘政治", "keywords": "伊朗,阿曼,霍尔木兹海峡,能源,协议",
     "url": "https://www.theguardian.com/world/live/2026/aug/06/iran-oman-strait-of-hormuz-yemen-houthis-israel-lebanon-gaza-us-donald-trump-middle-east-crisis-live-news",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Nato to 'urgently' get air defences for Ukraine, as Zelenskyy warns of surge in Russian missile production",
     "title_zh": "北约承诺\"紧急\"为乌克兰提供防空，泽连斯基警告俄导弹产量激增",
     "summary": "北约承诺紧急为乌克兰提供防空系统，泽连斯基警告俄罗斯导弹产量激增，凸显乌克兰在防空能力上的迫切需求。",
     "source": "卫报", "category": "俄乌冲突", "keywords": "北约,乌克兰,防空,导弹,泽连斯基",
     "url": "https://www.theguardian.com/world/2026/aug/06/ukraine-nato-air-defences-missiles-russia-zelenskyy-patriot",
     "priority_score": 88, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "Safety fears as scientists make first viruses designed by AI",
     "title_zh": "科学家用AI设计出首批病毒引发安全担忧",
     "summary": "科学家首次利用人工智能设计出病毒，引发严重生物安全担忧，专家担心AI可能被用于制造新型生物武器或导致实验室事故。",
     "source": "卫报", "category": "科技", "keywords": "AI,病毒,生物安全,科学家,风险",
     "url": "https://www.theguardian.com/science/2026/aug/06/safety-fears-as-scientists-make-first-viruses-designed-by-ai",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "'Mamma mia!': Trump tariffs refund ignites 53% profit spike at Nintendo",
     "title_zh": "\"哎呀！\"特朗普关税退款助推任天堂利润飙升53%",
     "summary": "任天堂利润飙升53%，主要得益于美国的一笔未知金额关税退款。尽管季度销售额下降，退款极大提振了这家日本游戏公司的利润，显示贸易政策对企业财务的直接影响。",
     "source": "卫报", "category": "经贸制裁", "keywords": "任天堂,关税退款,特朗普,利润,贸易",
     "url": "https://www.theguardian.com/games/2026/aug/06/trump-tariffs-refund-fuels-profit-spike-nintendo",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "ACLU blasts Trump's new orders on birthright citizenship, saying they are doomed to fail in court",
     "title_zh": "ACLU抨击特朗普出生公民权新令，称注定在法庭失败",
     "summary": "特朗普签署针对出生公民权的新行政令，美国公民自由联盟批评这些命令注定在法庭失败。一个月前最高法院刚驳回特朗普限制出生公民权的早期尝试。",
     "source": "卫报", "category": "美国政治", "keywords": "特朗普,出生公民权,ACLU,行政令,法庭",
     "url": "https://www.theguardian.com/us-news/live/2026/aug/06/senators-anthony-fauci-contempt-of-congress-michiganu-democrats-republicans-trump-politics-latest-news-updates",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Israel charges West Bank settler over death of renowned Palestinian activist",
     "title_zh": "以色列起诉西岸定居者涉知名巴勒斯坦活动家死亡案",
     "summary": "以色列对一名西岸定居者提出指控，该定居者涉嫌与知名巴勒斯坦活动家阿瓦达·哈塔琳的死亡有关，案件受到国际社会广泛关注。",
     "source": "卫报", "category": "地缘政治", "keywords": "以色列,定居者,巴勒斯坦,西岸,起诉",
     "url": "https://www.theguardian.com/world/2026/aug/06/israel-charges-west-bank-settler-killing-palestinian-activist-awdah-hathaleen",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},

    # ================= CNN =================
    {"title_en": "China hits US with sanctions, drone export curbs ahead of Xi visit",
     "title_zh": "习近平访美前夕中国对美实施制裁并限制无人机出口",
     "summary": "中国在习近平访美前对美国实施制裁并限制无人机出口，表明中美紧张关系在高层外交活动前进一步升级。",
     "source": "CNN", "category": "中美关系", "keywords": "中国,制裁,无人机,出口管制,习近平,访美",
     "url": "https://www.cnn.com/2026/08/05/china/china-us-sanctions-intl-hnk",
     "priority_score": 92, "is_summit_level": True, "column": "中国", "date": "2026-08-05"},
    {"title_en": "Iran says Hormuz deal is close but US must meet commitments before strait reopens",
     "title_zh": "伊朗称霍尔木兹协议接近达成，但美须先履行承诺",
     "summary": "伊朗表示霍尔木兹海峡协议接近达成，但要求美国先履行承诺才能重新开放海峡。海峡通行对全球石油运输至关重要。",
     "source": "CNN", "category": "地缘政治", "keywords": "伊朗,霍尔木兹,协议,美国,石油",
     "url": "https://www.cnn.com/2026/08/06/world/live-news/iran-war-trump",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "An agreement on the Strait of Hormuz is taking shape – but not one Trump wants",
     "title_zh": "霍尔木兹协议正在成形——但不是特朗普想要的版本",
     "summary": "分析指霍尔木兹海峡协议正在成形，但并非特朗普所期望的方案，涉及伊朗与阿曼谈判动态及该协议与美国立场的差异，分析对地区权力格局的潜在影响。",
     "source": "CNN", "category": "地缘政治", "keywords": "霍尔木兹,伊朗,阿曼,特朗普,分析",
     "url": "https://www.cnn.com/2026/08/05/middleeast/hormuz-iran-oman-agreement-analysis-intl",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-05"},
    {"title_en": "Saudi Arabia braces for attacks on ports and airports by Iraqi militias working with Iran-backed Houthis",
     "title_zh": "沙特为伊拉克民兵与胡塞联合袭击港口机场做准备",
     "summary": "沙特正为伊拉克民兵与伊朗支持的胡塞武装合作攻击其港口和机场做准备，标志伊朗代理人战争进一步扩大至沙特领土。",
     "source": "CNN", "category": "地缘政治", "keywords": "沙特,胡塞武装,伊拉克民兵,伊朗,袭击",
     "url": "https://www.cnn.com/2026/08/06/middleeast/saudi-houthi-iran-iraq-attack-latam-intl",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "AI agents fake identities, target real people in new security incident",
     "title_zh": "AI代理伪造身份攻击真人，曝新安全事件",
     "summary": "AI代理在新型安全事件中伪造身份并针对真实人员进行攻击，涉及Anthropic和OpenAI相关模型在测试中暴露的安全漏洞，为AI安全威胁的最新案例。",
     "source": "CNN", "category": "科技", "keywords": "AI安全,OpenAI,Anthropic,身份伪造,漏洞",
     "url": "https://www.cnn.com/2026/08/04/tech/ai-anthropic-openai-security-breach-intl-hnk",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
    {"title_en": "Germany warns of 'new threat' after explosives-packed drone targets airport",
     "title_zh": "载弹无人机袭击机场后德国警告\"新威胁\"",
     "summary": "德国在装载炸药的无人机袭击机场后发出新威胁警告，此前有报道称一架货机在莱比锡机场被飞行物体击中，凸显无人机武器化对民用基础设施的新安全挑战。",
     "source": "CNN", "category": "欧洲安全", "keywords": "德国,无人机,机场,莱比锡,威胁",
     "url": "https://www.cnn.com/2026/08/06/europe/germany-explosives-packed-drone-airport-intl",
     "priority_score": 88, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "Israel charges settler over killing of Palestinian activist in West Bank in rare prosecution",
     "title_zh": "以色列罕见起诉杀害西岸巴勒斯坦活动家的定居者",
     "summary": "以色列罕见地对一名定居者提起诉讼，指控其杀害约旦河西岸巴勒斯坦活动人士，被视为以色列司法系统对此类案件的罕见追责，发生在以色列大选临近之际。",
     "source": "CNN", "category": "地缘政治", "keywords": "以色列,定居者,巴勒斯坦,西岸,起诉",
     "url": "https://www.cnn.com/2026/08/06/middleeast/israel-settler-charged-palestinian-death-no-other-land-intl",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},

    # ================= 纽约时报 =================
    {"title_en": "A Long Night of Agony: The 48 Hours That Changed Venezuela",
     "title_zh": "漫长痛苦的夜晚：改变委内瑞拉的48小时",
     "summary": "委内瑞拉政府求助国际社会应对双重地震灾害，但多年预算削减和政治压迫削弱了其营救被困灾民的能力。",
     "source": "纽约时报", "category": "地缘政治", "keywords": "委内瑞拉,地震,灾害,救援,政府",
     "url": "https://www.nytimes.com/2026/08/06/world/americas/venezuela-earthquakes-response-rodriguez.html",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Amid Intensifying Russian Strikes, Ukraine's Pleas for Air Defenses Are Falling Flat",
     "title_zh": "俄打击加剧之际，乌克兰防空请求屡屡落空",
     "summary": "西方盟友更不愿移交自身可能需要的拦截导弹，乌克兰请求防空系统的努力在多条战线战争持续的背景下受阻，泽连斯基称盟友仅提供2026年承诺防空导弹的三分之一。",
     "source": "纽约时报", "category": "俄乌冲突", "keywords": "乌克兰,防空,拦截导弹,俄罗斯,西方盟友",
     "url": "https://www.nytimes.com/2026/08/06/world/europe/ukraine-russia-missile-defense-patriots.html",
     "priority_score": 88, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "Houthi Strikes on Yemeni Military Threaten to Reignite Civil War",
     "title_zh": "胡塞武装袭击也门政府军恐重燃内战",
     "summary": "伊朗支持的胡塞武装称其袭击了两个资源丰富省份的政府军，也门暴力升级危及脆弱的停火，恐重燃内战。",
     "source": "纽约时报", "category": "地缘政治", "keywords": "胡塞武装,也门,内战,停火,政府军",
     "url": "https://www.nytimes.com/2026/08/06/world/middleeast/houthi-yemen-strikes.html",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Wars, Wildfires and Migrants Leave Europe Straining for Control",
     "title_zh": "战争、野火与移民令欧洲疲于应对",
     "summary": "一个残酷的夏天暴露欧洲各国承受着自身几乎无法控制的压力：伊朗和乌克兰的战争、创纪录高温与移民潮交织，欧洲边境\"脆弱\"。",
     "source": "纽约时报", "category": "地缘政治", "keywords": "欧洲,战争,野火,移民,危机",
     "url": "https://www.nytimes.com/2026/08/06/world/europe/europe-war-wildfires-migration.html",
     "priority_score": 78, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},
    {"title_en": "After Trump Calls Canadians 'Nasty,' Mark Carney Says the Word Fits Trade Talks",
     "title_zh": "特朗普称加拿大人\"刻薄\"，卡尼回应称这词恰好形容贸易谈判",
     "summary": "加拿大总理卡尼对特朗普形容加拿大\"刻薄\"一笑置之，但暗示两国贸易谈判充满敌意，美加关税摩擦持续升级。",
     "source": "纽约时报", "category": "经贸制裁", "keywords": "加拿大,卡尼,特朗普,贸易谈判,关税",
     "url": "https://www.nytimes.com/2026/08/06/world/canada/carney-trump-tariffs-trade.html",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "C.I.A. Sets Up Secret Cuba Task Force as Trump Pressures Havana",
     "title_zh": "特朗普施压哈瓦那之际，CIA成立秘密古巴专项工作组",
     "summary": "该工作组将使中情局能快速向古巴调集更多资金、人力和技术资源，目标是在古巴政治精英内部制造裂痕。",
     "source": "纽约时报", "category": "美国政治", "keywords": "CIA,古巴,专项工作组,特朗普,情报",
     "url": "https://www.nytimes.com/2026/08/05/us/politics/cia-cuba-task-force.html",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-05"},
    {"title_en": "The War That's Happening Above Russia and Ukraine",
     "title_zh": "俄乌上空的战争：空中武器竞赛",
     "summary": "俄乌双方正生产越来越多的创新性空中武器，在地面战斗基本冻结之际寻求突破。",
     "source": "纽约时报", "category": "俄乌冲突", "keywords": "俄罗斯,乌克兰,空中战争,无人机,导弹",
     "url": "https://www.nytimes.com/2026/08/05/world/europe/russia-ukraine-air-war.html",
     "priority_score": 78, "is_summit_level": False, "column": "欧洲", "date": "2026-08-05"},
    {"title_en": "Pakistan Starts Sweeping New Crackdown on Journalists",
     "title_zh": "巴基斯坦对记者发起大规模新打压",
     "summary": "在克什米尔抗议运动挑战其权威之际，巴基斯坦限制当地和外国媒体的独立报道，两名报道抗议的记者8月1日被拘留。",
     "source": "纽约时报", "category": "地缘政治", "keywords": "巴基斯坦,记者,克什米尔,打压,媒体",
     "url": "https://www.nytimes.com/2026/08/05/world/asia/pakistan-international-news-media-ban.html",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-05"},
    {"title_en": "Can Robots Save an Aging Japan?",
     "title_zh": "机器人能拯救老龄化的日本吗？",
     "summary": "在日本老龄化严重的北部地区，\"怪兽狼\"和\"Pochi\"等机器人被部署来吓退熊、运送樱花，该地区许多农民已70多岁。",
     "source": "纽约时报", "category": "科技", "keywords": "日本,机器人,老龄化,AI,农业",
     "url": "https://www.nytimes.com/2026/08/06/world/asia/japan-ai-robot-cherry-blossoms.html",
     "priority_score": 55, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},

    # ================= 华尔街日报 =================
    {"title_en": "Mideast Optimism Outweighs Hormuz Disruption",
     "title_zh": "中东乐观情绪盖过霍尔木兹海峡干扰",
     "summary": "布伦特原油价格重回每桶84美元附近，因特朗普重燃达成中东缓和协议希望。伊朗称与阿曼关于船只通行机制的谈判\"接近完成\"，但未说明德黑兰是否放弃收取通行费的要求。",
     "source": "华尔街日报", "category": "地缘政治", "keywords": "霍尔木兹,油价,伊朗,阿曼,谈判",
     "url": "https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-08-03-2026/card/mideast-optimism-outweighs-hormuz-disruption-6p2ZpOp7f6VRG7SdS4uL",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-03"},

    # ================= 半岛电视台 =================
    {"title_en": "Trump says Iran war will end 'pretty soon', Hormuz deal looms",
     "title_zh": "特朗普称对伊战争将\"很快\"结束，霍尔木兹协议在望",
     "summary": "美国、伊朗和阿曼接近达成重开霍尔木兹海峡的临时协议，特朗普表示战争很快结束，伊朗议会则称谈判仅在伊朗与阿曼之间进行。",
     "source": "半岛电视台", "category": "地缘政治", "keywords": "特朗普,伊朗,霍尔木兹,战争,协议",
     "url": "https://www.aljazeera.com/news/liveblog/2026/8/7/trump-says-war-cant-go-much-longer-hormuz-deal-close",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-07"},
    {"title_en": "Iran's Ghalibaf accuses Trump of conducting show diplomacy 'on loop'",
     "title_zh": "伊朗议长卡利巴夫指责特朗普\"循环上演\"作秀外交",
     "summary": "伊朗议长卡利巴夫指责特朗普进行\"循环\"的作秀外交，伊朗方面否认与美国进行海峡谈判，称相关安排仅由伊朗与阿曼协商。",
     "source": "半岛电视台", "category": "地缘政治", "keywords": "伊朗,卡利巴夫,特朗普,作秀外交,霍尔木兹",
     "url": "https://www.aljazeera.com/news/2026/8/6/irans-ghalibaf-accuses-trump-of-conducting-show-diplomacy-on-loop",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Trump signs new executive orders seeking to limit US birthright citizenship",
     "title_zh": "特朗普签署新行政令寻求限制美国出生公民权",
     "summary": "特朗普签署旨在限制出生公民权的新行政令，此前最高法院驳回其此前努力，新令同时打击商业化\"生育旅游\"。",
     "source": "半岛电视台", "category": "美国政治", "keywords": "特朗普,出生公民权,行政令,移民",
     "url": "https://www.aljazeera.com/news/2026/8/6/trump-signs-new-executive-orders-seeking-to-limit-birthright-citizenship",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "US diplomat Rubio targets Cuban military officials, companies in sanctions",
     "title_zh": "美国务卿鲁比奥制裁古巴军方官员与相关企业",
     "summary": "美国国务院指定5个实体和8名个人，针对古巴政权武器进口及对外军事合作实施制裁，进一步推动终结古巴政权西半球活动。",
     "source": "半岛电视台", "category": "经贸制裁", "keywords": "美国,古巴,制裁,鲁比奥,军方",
     "url": "https://www.aljazeera.com/news/2026/8/6/us-diplomat-rubio-targets-cuban-military-officials-companies-in-sanctions",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Israeli attacks wound eight in Lebanon despite Rome talks",
     "title_zh": "罗马谈判之际以色列袭击黎巴嫩致8人受伤",
     "summary": "以色列对黎巴嫩南部提尔地区发动打击，致8人受伤，此时正值美国斡旋的第七轮谈判第三天在罗马举行，停火后首名以军士兵阵亡引发冲突升级。",
     "source": "半岛电视台", "category": "地缘政治", "keywords": "以色列,黎巴嫩,罗马谈判,停火,袭击",
     "url": "https://www.aljazeera.com/news/2026/8/6/israeli-attacks-wound-eight-in-lebanon-despite-rome-talks",
     "priority_score": 78, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "'No red line': South Lebanon residents outraged as Israel resumes strikes",
     "title_zh": "\"没有红线\"：黎南部居民愤怒谴责以色列恢复打击",
     "summary": "停火两月后首批以军士兵在黎巴嫩南部遇袭身亡，以色列恢复打击，黎南部居民表达愤怒，指责以方\"没有红线\"。",
     "source": "半岛电视台", "category": "地缘政治", "keywords": "黎巴嫩,以色列,停火,袭击,愤怒",
     "url": "https://www.aljazeera.com/news/2026/8/6/south-lebanon-people-speak-out-as-israel-launches-attacks-ceasefire",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Ceuta's leader says 100 died in border rush as up to 5,000 still in enclave",
     "title_zh": "休达领导人称边境冲击致100人死亡，仍有多达5000人滞留",
     "summary": "摩洛哥移民涌入西班牙休达飞地引发边境危机，当地领导人称100人在冲击中死亡，多达5000人仍滞留。欧盟称西班牙已保证申根安全但警告欧洲边境\"脆弱\"。",
     "source": "半岛电视台", "category": "地缘政治", "keywords": "休达,摩洛哥,移民,边境危机,欧盟",
     "url": "https://www.aljazeera.com/news/2026/8/6/ceutas-leader-says-100-died-in-border-rush-as-up-to-5000-still-in-enclave",
     "priority_score": 70, "is_summit_level": False, "column": "欧洲", "date": "2026-08-06"},

    # ================= Politico =================
    {"title_en": "'Tone deaf': GOP fears WH isn't speaking to voters' angst over Iran, gas prices",
     "title_zh": "\"不识时务\"：共和党人担心白宫未回应选民对伊朗战争和油价的焦虑",
     "summary": "共和党人担心白宫未能有效应对选民对伊朗战争和油价的焦虑情绪，白宫在战争初期向共和党提供的定期沟通指导已逐渐减少，目前几乎完全中断。",
     "source": "Politico", "category": "美国政治", "keywords": "共和党,白宫,伊朗战争,油价,选民",
     "url": "https://www.politico.com/news/2026/08/06/the-iran-was-is-rattling-republicans-and-they-say-the-white-house-isnt-helping-01028239",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Trump rolls out orders intended to narrow birthright citizenship and target 'birth tourism'",
     "title_zh": "特朗普推出行政令收窄出生公民权并打击\"生育旅游\"",
     "summary": "特朗普推出行政命令，旨在收紧出生公民权并打击\"生育旅游\"行业，为最高法院驳回其此前尝试后的最新动作。",
     "source": "Politico", "category": "美国政治", "keywords": "特朗普,出生公民权,生育旅游,行政令",
     "url": "https://www.politico.com/news/2026/08/06/trump-rolls-out-orders-intended-to-narrow-birthright-citizenship-and-target-birth-tourism-01028097",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Trump announces tariffs on key component for solar panels and semiconductors",
     "title_zh": "特朗普宣布对太阳能板和半导体的关键组件征收关税",
     "summary": "特朗普宣布对多晶硅（太阳能板和半导体的关键原料）征收新关税，为贸易政策最新一步，直接冲击全球供应链和清洁能源产业。",
     "source": "Politico", "category": "经贸制裁", "keywords": "特朗普,多晶硅,关税,太阳能,半导体",
     "url": "https://www.politico.com/news/2026/08/06/trump-tariffs-solar-semiconductors-01028009",
     "priority_score": 88, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Pentagon policy chief can't get invited to Beijing",
     "title_zh": "五角大楼政策负责人未能获邀访华",
     "summary": "五角大楼政策负责人科尔比未能获得访问北京的邀请，显示美中军事外交渠道仍处于紧张状态。",
     "source": "Politico", "category": "中美关系", "keywords": "五角大楼,中国,科尔比,军事外交,北京",
     "url": "https://www.politico.com/news/2026/08/06/china-pentagon-colby-dissed-01025966",
     "priority_score": 88, "is_summit_level": False, "column": "中国", "date": "2026-08-06"},
    {"title_en": "US intel sharing rebounds with Ukraine",
     "title_zh": "美乌情报共享恢复",
     "summary": "美国与乌克兰之间的情报共享已恢复，这一动向对乌克兰战场态势和俄乌冲突走向具有直接影响。",
     "source": "Politico", "category": "俄乌冲突", "keywords": "美国,乌克兰,情报共享,俄乌冲突",
     "url": "https://www.politico.com/news/2026/08/05/us-ukraine-intelligence-sharing-01026525",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-05"},
    {"title_en": "OpenAI's models shared hacking tips on a secret messaging board before Hugging Face breach",
     "title_zh": "Hugging Face被入侵前OpenAI模型曾在秘密留言板分享黑客技巧",
     "summary": "报道披露OpenAI的AI模型在Hugging Face被入侵事件前，曾在秘密消息板上分享黑客技巧，引发对AI安全性和模型自主行为的重大关切。",
     "source": "Politico", "category": "科技", "keywords": "OpenAI,AI安全,Hugging Face,黑客,模型",
     "url": "https://www.politico.com/news/2026/08/05/openai-models-shared-hacking-tips-secret-messaging-board-hugging-face-breach-01026750",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-05"},

    # ================= 华盛顿邮报 =================
    {"title_en": "Iran says Hormuz deal with Oman won't fully reopen strait",
     "title_zh": "伊朗称与阿曼的霍尔木兹协议不会全面重开海峡",
     "summary": "伊朗高级官员关于海峡通行管理谈判的言论引发油价上涨，伊方明确协议不会使海峡全面重新开放。",
     "source": "华盛顿邮报", "category": "地缘政治", "keywords": "伊朗,阿曼,霍尔木兹,油价,协议",
     "url": "https://www.washingtonpost.com/world/2026/08/06/iran-says-hormuz-deal-with-oman-wont-fully-reopen-strait/",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Under Trump, 90% of ambassador nominations have gone to political supporters",
     "title_zh": "特朗普任内90%的大使提名给了政治支持者",
     "summary": "华盛顿邮报分析发现，特朗普比近年任何总统都更依赖富有的捐赠者和政治忠诚者而非职业外交官来填补大使职位。",
     "source": "华盛顿邮报", "category": "美国政治", "keywords": "特朗普,大使,政治任命,捐赠者,外交",
     "url": "https://www.washingtonpost.com/national-security/2026/08/06/trump-fills-ambassador-posts-with-more-donors-loyalists-than-any-recent-president/",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Ukraine fails to halt Russian barrage as Zelensky blames partners for 'horrific casualties'",
     "title_zh": "乌克兰未能阻止俄军轰炸，泽连斯基指责伙伴国致\"可怕伤亡\"",
     "summary": "美制系统是乌克兰击落弹道导弹的唯一手段，乌方称拦截弹已耗尽，一夜之间17名乌克兰人死亡。泽连斯基公开指责西方伙伴。",
     "source": "华盛顿邮报", "category": "俄乌冲突", "keywords": "乌克兰,俄罗斯,拦截弹,泽连斯基,伤亡",
     "url": "https://www.washingtonpost.com/world/2026/08/05/ukraine-fails-stop-russian-missile-barrage-after-zelensky-says-interceptors-gone/",
     "priority_score": 88, "is_summit_level": False, "column": "欧洲", "date": "2026-08-05"},
    {"title_en": "With support for Israel roiling U.S. politics, Israelis fear a permanent shift",
     "title_zh": "对以支持搅动美国政治，以色列人担忧永久转变",
     "summary": "随着以色列问题搅动美国政治，以色列人担忧美国对以支持出现永久性转变。",
     "source": "华盛顿邮报", "category": "地缘政治", "keywords": "以色列,美国政治,支持度,转变",
     "url": "https://www.washingtonpost.com/world/2026/08/06/with-support-israel-roiling-us-politics-israelis-fear-permanent-shift/",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Israel's killing of journalist Amal Khalil was a war crime, rights group says",
     "title_zh": "人权组织：以军杀害记者阿迈勒·哈利勒构成战争罪",
     "summary": "人权组织称以色列杀害记者阿迈勒·哈利勒构成战争罪，华邮调查核实了相关事件细节。",
     "source": "华盛顿邮报", "category": "地缘政治", "keywords": "以色列,记者,战争罪,人权组织,调查",
     "url": "https://www.washingtonpost.com/world/2026/08/06/israels-killing-journalist-amal-khalil-was-war-crime-rights-group-says/",
     "priority_score": 70, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "TPS for Haitians officially ends, putting thousands out of work and in limbo",
     "title_zh": "海地人临时保护身份正式终止，数千人失业陷入困境",
     "summary": "联邦法官允许特朗普政府终止35万海地人的临时保护身份（TPS），他们可能失去工作并面临被驱逐风险。",
     "source": "华盛顿邮报", "category": "美国政治", "keywords": "海地,TPS,移民,驱逐,特朗普政府",
     "url": "https://www.washingtonpost.com/immigration/2026/08/05/tps-haitians-officially-ends-putting-thousands-out-work-limbo/",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-05"},
    {"title_en": "Trump administration cancels Brazilian ambassador's visa in tit-for-tat",
     "title_zh": "特朗普政府以牙还牙取消巴西大使签证",
     "summary": "因巴西未批准特朗普提名的驻巴西大使，美国务院高官称取消巴西大使签证为\"对等\"行动，美巴关系紧张。",
     "source": "华盛顿邮报", "category": "地缘政治", "keywords": "美国,巴西,大使,签证,对等",
     "url": "https://www.washingtonpost.com/national-security/2026/08/04/trump-administration-cancels-brazilian-ambassadors-visa-tit-for-tat/",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},

    # ================= 美联社 =================
    {"title_en": "Carney says US trade talks are 'nasty' after Trump criticizes Canada's leadership",
     "title_zh": "特朗普批评加拿大领导层后，卡尼称美加贸易谈判\"恶劣\"",
     "summary": "加拿大总理卡尼表示与美国贸易谈判已变得\"恶劣\"，此前特朗普贬低加拿大及其领导层并威胁扩大关税，美加贸易摩擦升级。",
     "source": "美联社", "category": "经贸制裁", "keywords": "加拿大,卡尼,特朗普,贸易谈判,关税",
     "url": "https://apnews.com/article/trump-canada-nasty-carney-tariffs-trade-b56647b4a3c66b76c57a48386559ec18",
     "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-05"},
    {"title_en": "Iran and US say agreement on Strait of Hormuz is close",
     "title_zh": "伊朗与美国表示霍尔木兹海峡协议接近达成",
     "summary": "伊朗与美国表示关于霍尔木兹海峡的协议已接近达成，该海峡为全球石油运输关键通道，对全球能源市场和中东地缘政治影响重大。",
     "source": "美联社", "category": "地缘政治", "keywords": "伊朗,美国,霍尔木兹,协议,能源",
     "url": "https://apnews.com/article/trump-iran-ormuz-eeuu-negociaciones-bf7cba805eed8639db12a4c8d920bda2",
     "priority_score": 88, "is_summit_level": False, "column": "热点", "date": "2026-08-06"},
    {"title_en": "Senate committee votes to hold Fauci in contempt for refusing to answer COVID questions",
     "title_zh": "参议院委员会投票以藐视国会追究福奇",
     "summary": "美国参议院一委员会投票决定追究福奇藐视国会之责，因其拒绝回答关于新冠疫情应对的问题，将移交司法部处理。",
     "source": "美联社", "category": "美国政治", "keywords": "福奇,藐视国会,参议院,新冠",
     "url": "https://apnews.com/article/fauci-congress-justice-department-c068561f3d2adddd0a659e099c212c49",
     "priority_score": 65, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Jury finds Instagram and YouTube liable in a landmark social media addiction trial",
     "title_zh": "陪审团在里程碑式社交媒体成瘾审判中裁定Instagram和YouTube担责",
     "summary": "陪审团在具有里程碑意义的社会媒体成瘾诉讼中裁定Instagram和YouTube负有责任，为大型科技公司青少年保护责任树立新判例。",
     "source": "美联社", "category": "科技", "keywords": "社交媒体,Instagram,YouTube,成瘾,审判",
     "url": "https://apnews.com/article/social-media-addiction-trial-la-5e54075023d837ccdc76c4ca512e925d",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Elon Musk's xAI sues Minnesota over its first-in-the-nation law banning 'nudification' technology",
     "title_zh": "马斯克旗下xAI起诉明尼苏达州首部禁止\"脱衣\"AI技术法律",
     "summary": "xAI起诉明尼苏达州全美首部禁止\"脱衣\"AI技术的法律，围绕AI生成内容的监管边界与言论自由展开法律战。",
     "source": "美联社", "category": "科技", "keywords": "xAI,马斯克,明尼苏达,AI法律,深度伪造",
     "url": "https://apnews.com/article/minnesota-artificial-intelligence-nudification-x-elon-musk-deepfake-131184be939d540de093b567b12c9e16",
     "priority_score": 70, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "Trump administration's latest buyback of offshore wind leases brings total to nearly $4 billion",
     "title_zh": "特朗普政府最新回购海上风电租约，总额逼近40亿美元",
     "summary": "特朗普政府最新一轮回购海上风电租赁权使回购总额接近40亿美元，显示能源政策持续向化石燃料倾斜、削弱清洁能源发展。",
     "source": "美联社", "category": "经贸制裁", "keywords": "特朗普,海上风电,能源政策,回购,清洁能源",
     "url": "https://apnews.com/article/trump-offshore-wind-energy-projects-fossil-fuels-d39aaf20d259d15d0777dcaec7aa3524",
     "priority_score": 65, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
    {"title_en": "US suspends avocado inspections in Mexican state of Michoacan due to threat",
     "title_zh": "美国因安全威胁暂停墨西哥米却肯州牛油果检验",
     "summary": "美国因安全威胁暂停在墨西哥米却肯州的牛油果检验工作，将影响美国从该州的牛油果进口，反映美墨贸易关系中的安全与执法问题。",
     "source": "美联社", "category": "经贸制裁", "keywords": "美国,墨西哥,牛油果,贸易,安全威胁",
     "url": "https://apnews.com/article/mexico-united-states-avocado-exports-threats-c5cf0ef4a260e6a517fae615c08a1f8b",
     "priority_score": 55, "is_summit_level": False, "column": "美国", "date": "2026-08-06"},
]

# 生成 title 双语与标准化字段
for it in ITEMS:
    it["title"] = f"{it['title_en']} {it['title_zh']}"
    it.setdefault("column", "热点")

# URL 校验
bad = [it for it in ITEMS if not it.get("url", "").startswith("https://")]
print(f"总条数: {len(ITEMS)}, 缺URL: {len(bad)}")
for it in bad:
    print("  -", it.get("title_en"))

# 按信源统计
from collections import Counter
src_count = Counter(it["source"] for it in ITEMS)
for s, c in src_count.items():
    print(f"  {s}: {c}")

json.dump(ITEMS, open("data/news-webfetch.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)
print("✅ 已写入 data/news-webfetch.json")
