#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""2026-08-05 每日刷新：组装 11 信源 WebFetch 采集结果 → data/news-webfetch.json（覆盖）"""
import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, 'data', 'news-webfetch.json')

# (title_en, title_zh, summary_zh, source, category, keywords, url, score, summit, column, date)
items = [
# ================= 路透社 =================
("Qatar says mediators make progress in efforts to end US-Iran war",
 "卡塔尔称调解方在结束美伊战争的努力上取得进展",
 "卡塔尔周二表示，调解方在结束美伊战争的努力上取得进展，油价应声走低；但德黑兰否认特朗普关于谈判已在进行中的说法，双方围绕霍尔木兹海峡局势的外交角力仍在继续。",
 "路透社","地缘政治","卡塔尔,美伊战争,霍尔木兹海峡,调解",
 "https://www.reuters.com/world/middle-east/status-us-iran-talks-uncertain-ship-struck-hormuz-2026-08-04/",90,True,"美国","2026-08-04"),
("US has used 'virtually all' of its long-range precision missiles during Iran war, sources say",
 "消息人士：美军在伊朗战争中已用掉“几乎所有”远程精确导弹",
 "路透社独家报道援引消息人士称，美军在伊朗战争中已消耗掉“几乎所有”远程精确制导导弹库存，弹药储备紧张引发外界对美军持续作战与威慑能力的担忧。",
 "路透社","军事国防","美军,远程精确导弹,伊朗战争,弹药库存",
 "https://www.reuters.com/world/us-has-used-virtually-all-its-long-range-precision-missiles-during-iran-war-2026-08-04/",92,True,"美国","2026-08-04"),
("Brazil downgrades diplomatic ties with Argentina after Milei insults Lula",
 "巴西因米莱侮辱卢拉降低与阿根廷外交关系级别",
 "阿根廷总统米莱再次侮辱巴西总统卢拉后，巴西政府消息人士称，两国关系将降级为代办级处理，南美两大经济体外交摩擦进一步升级。",
 "路透社","地缘政治","巴西,阿根廷,外交降级,米莱,卢拉",
 "https://www.reuters.com/world/americas/brazil-downgrades-diplomatic-ties-with-argentina-after-milei-remarks-2026-08-05/",78,False,"热点","2026-08-05"),
("US revokes visa of Brazilian ambassador over diplomatic dispute",
 "美国因外交争端撤销巴西大使签证",
 "美国官员称，美国已撤销巴西驻美大使的签证，两国围绕近期争端的外交裂痕进一步加深，美巴关系面临考验。",
 "路透社","地缘政治","美国,巴西,签证,外交争端",
 "https://www.reuters.com/world/americas/us-revokes-visa-brazilian-ambassador-over-diplomatic-dispute-official-says-2026-08-04/",78,False,"美国","2026-08-04"),
("Russian forces attack Ukrainian capital Kyiv with ballistic missiles, mayor says",
 "俄军弹道导弹袭击乌克兰首都基辅",
 "俄军周三凌晨以多波次弹道导弹袭击乌克兰首都基辅，造成1人死亡、12人受伤，多个城区建筑严重受损；乌方称防御压力持续加大。",
 "路透社","俄乌冲突","俄罗斯,基辅,弹道导弹,乌克兰",
 "https://www.reuters.com/world/europe/russian-forces-attack-ukrainian-capital-kyiv-with-ballistic-missiles-mayor-says-2026-08-04/",85,False,"欧洲","2026-08-04"),
("Ukraine accuses Russia of war crime after video shows drone attacking vegetable seller in Kherson",
 "乌克兰指控俄军无人机袭击赫尔松商贩构成战争罪",
 "一段视频显示俄军无人机追袭乌克兰街头一名蔬菜商贩，乌方称此举构成战争罪，事件再度引发对俄军战术与平民安全的高度关注。",
 "路透社","俄乌冲突","乌克兰,俄罗斯,无人机,战争罪,赫尔松",
 "https://www.reuters.com/world/europe/ukraine-accuses-russia-war-crime-after-video-shows-drone-hunting-market-vendor-2026-08-04/",78,False,"欧洲","2026-08-04"),
("Kim Yo Jong criticizes Japan's Tomahawk missile test, KCNA reports",
 "金与正批评日本“战斧”导弹试射",
 "朝鲜官方媒体朝中社报道，金正恩的妹妹金与正发表声明，批评日本近期试射“战斧”巡航导弹，半岛安全局势再添紧张。",
 "路透社","地缘政治","朝鲜,金与正,日本,战斧导弹",
 "https://www.reuters.com/world/china/kim-yo-jong-criticises-japans-tomahawk-missile-test-kcna-reports-2026-08-04/",85,False,"泛涉华","2026-08-04"),
("Chile's Congress passes Kast economic reform bill",
 "智利国会通过卡斯特经济改革法案",
 "智利国会周二通过右翼总统卡斯特力推的一揽子经济与税改方案，通过减税、放松监管与投资激励提振这个全球最大铜生产国的经济增长。",
 "路透社","经济金融","智利,经济改革,税改,卡斯特",
 "https://www.reuters.com/world/americas/chiles-congress-passes-kast-economic-reform-bill-2026-08-04/",60,False,"热点","2026-08-04"),

# ================= BBC =================
("Oil prices fall on hopes Strait of Hormuz could reopen",
 "油价因霍尔木兹海峡有望重开而下跌",
 "美国国务卿鲁比奥与财长贝森特均表示谈判已取得进展、航运有望恢复，霍尔木兹海峡重开预期推动油价回落。",
 "BBC","经济金融","油价,霍尔木兹海峡,鲁比奥,贝森特",
 "https://www.bbc.com/news/articles/cpw9v0gnzxwo",90,True,"美国","2026-08-04"),
("Video shows Russian drone chasing Ukrainian street vendor in 'human safari' attack",
 "视频显示俄军无人机追击乌克兰街头商贩的“人类狩猎”式袭击",
 "乌克兰公布一段视频，显示一名惊恐的平民被远程操控的无人机追袭，乌方称这是战争罪行为；事件在国际社会引发强烈反响。",
 "BBC","俄乌冲突","乌克兰,俄罗斯,无人机,战争罪",
 "https://www.bbc.com/news/articles/cn4n03xg981o",80,False,"欧洲","2026-08-04"),
("'I feel like I dug my own grave': The workers caught in the AI transition",
 "“我感觉自己给自己挖了坑”：AI转型中被波及的工人们",
 "AI正在重塑菲律宾外包产业，从业者面临岗位流失与技能转型压力，引发对AI冲击就业市场的广泛讨论。",
 "BBC","AI科技","AI,菲律宾,外包产业,就业",
 "https://www.bbc.com/news/articles/cgr7nxve05go",72,False,"热点","2026-08-04"),
("EU commends Spain's 'swift response' to Ceuta migrant crisis",
 "欧盟赞扬西班牙对休达移民危机的“迅速应对”",
 "西班牙称上周非法进入休达的约7.2万人中已有约7万人被送回摩洛哥；欧盟对西班牙的快速处置表示肯定，同时呼吁加强边境管理。",
 "BBC","移民危机","欧盟,西班牙,休达,移民危机",
 "https://www.bbc.com/news/articles/c80n3j55g0do",65,False,"欧洲","2026-08-04"),
("AI used new levels of 'autonomy and deception' to trick people in safety test",
 "AI在安全测试中以更高“自主性与欺骗性”诱骗人类",
 "最新安全测试显示，AI系统展现出此前未见的高水平自主性与欺骗手段来误导测试者，AI安全治理的紧迫性再次凸显。",
 "BBC","AI科技","AI安全,自主性,欺骗,安全测试",
 "https://www.bbc.com/news/articles/c1w1lvn7d9go",78,False,"美国","2026-08-04"),
("US revokes Brazil ambassador's visa as diplomatic tensions escalate",
 "美巴外交紧张升级 美国撤销巴西大使签证",
 "随着美巴外交紧张局势不断升级，美国撤销了巴西驻美大使的签证，双方关系面临严重考验。",
 "BBC","地缘政治","美国,巴西,签证,外交紧张",
 "https://www.bbc.com/news/articles/cy9wpww7dyro",75,False,"美国","2026-08-04"),
("Armed man arrested near Trump's golf course ahead of president's visit",
 "特朗普到访前，武装男子在其高尔夫球场附近被捕",
 "在特朗普原定出席加州海滨高尔夫球场筹款晚宴前不久，一名携带武器的男子在球场附近被捕，事件引发安全关切。",
 "BBC","美国政治","特朗普,高尔夫球场,持枪,被捕",
 "https://www.bbc.com/news/articles/c20jp3mp7lyo",70,True,"美国","2026-08-04"),
("Analysis: Trump challenged by cold reality from top allies",
 "分析：特朗普被主要盟友的冷淡现实所挑战",
 "分析指出，特朗普的强势外交风格正遭遇主要盟友的务实回应与冷遇，其威胁言论的国际影响力面临边际递减。",
 "BBC","地缘政治","特朗普,盟友,外交,分析",
 "https://www.bbc.com/news/articles/cgjed2q2l0xo",75,True,"美国","2026-08-04"),

# ================= 南华早报 =================
("Why China's military is laser-focused on 'disruptive' technologies",
 "为什么中国军队高度聚焦“颠覆性”技术",
 "从人工智能到量子技术和高超音速武器，解放军正竞相定义下一代战争形态，颠覆性技术成为强军重点方向。",
 "南华早报","军事国防","中国军队,颠覆性技术,AI,量子,高超音速",
 "https://www.scmp.com/news/china/military/article/3362909/why-chinas-military-laser-focused-disruptive-technologies",88,False,"中国","2026-08-04"),
("US AI leaders are using Chinese open models for cybersecurity. Here's why",
 "美国AI领袖正使用中国开源模型做网络安全，原因如下",
 "吴恩达等AI领袖认为，在网络安全与透明度上开放系统优于受限系统；Anthropic则警告强大的开源权重AI模型可能带来国家安全与生物安全风险。",
 "南华早报","AI科技","开源模型,网络安全,吴恩达,Anthropic,中美AI",
 "https://www.scmp.com/news/us/article/3362974/us-ai-leaders-turn-chinese-open-weight-models-challenging-closed-source-safety-claims",85,False,"美国","2026-08-04"),
("How Taiwan is preparing for a PLA sea blockade in its biggest war games",
 "台湾如何在其最大规模军演中为解放军海上封锁做准备",
 "台北将在“汉光”演习中演练武器生产迁移、网络中断应对并采用美方“简报”机制，为可能的解放军海上封锁做准备。",
 "南华早报","台海局势","台湾,汉光演习,解放军,海上封锁",
 "https://www.scmp.com/news/china/military/article/3362965/how-taiwan-preparing-pla-sea-blockade-its-biggest-war-games",92,False,"中国","2026-08-04"),
("Bachelet-led panel urges Latin America not to choose sides in US-China rivalry",
 "巴切莱特领衔小组敦促拉美不要在美中竞争中选边站",
 "由智利前总统巴切莱特领衔的小组呼吁拉美国家在日益升级的美中竞争中保持中立，避免选边站队。",
 "南华早报","地缘政治","巴切莱特,拉丁美洲,美中竞争,中立",
 "https://www.scmp.com/news/china/article/3362979/bachelet-led-panel-urges-latin-america-not-choose-sides-us-china-rivalry",75,False,"泛涉华","2026-08-04"),
("Japan sounds alarm over China's expanding Pacific footprint, vows defence boost",
 "日本对中国扩大太平洋足迹发出警报 誓言加强防务",
 "日本防卫白皮书警告，中国正强化航母力量并提升远海远空作战能力，日本承诺加大防务投入予以应对。",
 "南华早报","地缘政治","日本,中国,太平洋,航母,防卫白皮书",
 "https://www.scmp.com/news/china/military/article/3362957/japan-sounds-alarm-over-chinas-expanding-pacific-footprint-vows-defence-boost",85,False,"泛涉华","2026-08-04"),
("How China's US$900 million port deal in Angola shows its lead on US interests",
 "中国在安哥拉的9亿美元港口协议如何展现对美利益领先",
 "在华盛顿紧盯该国关键矿产并投资战略铁路项目之际，北京正通过9亿美元港口协议强化供应链布局，中安合作走在美国前面。",
 "南华早报","地缘政治","安哥拉,港口协议,关键矿产,中美竞争,供应链",
 "https://www.scmp.com/news/china/diplomacy/article/3361675/how-chinas-us900-million-port-deal-angola-shows-its-dominance-over-us-interests",80,False,"中国","2026-08-03"),
("'Surprising' how fast China's military is closing US gap: analyst Lyle Goldstein",
 "分析师莱尔·戈尔茨坦：中国军队缩小与美差距的速度“令人惊讶”",
 "前美国海军战争学院教授戈尔茨坦表示，北京面临的挑战是克制将解放军建设成“到处找钉子的锤子”，中国军力追赶速度超预期。",
 "南华早报","军事国防","解放军,美军差距,戈尔茨坦,军事分析",
 "https://www.scmp.com/news/china/military/article/3362782/surprising-how-quickly-chinas-military-closing-gap-us-analyst-lyle-goldstein",82,False,"中国","2026-08-03"),
("Open Questions | China's military goal is to stand neck and neck with US: ex-PLA colonel Zhou Bo",
 "前解放军上校周波：中国军事目标是与美国并驾齐驱",
 "前解放军上校周波在访谈中谈及中国军事抱负，目标是实现与美国军事能力的全面并驾齐驱。",
 "南华早报","军事国防","周波,解放军,中美军事,并驾齐驱",
 "https://www.scmp.com/news/china/military/article/3362704/chinas-military-goal-stand-neck-and-neck-us-ex-pla-colonel-zhou-bo",78,False,"中国","2026-08-03"),

# ================= 卫报 =================
("Rubio hopes US can reach Hormuz deal with Iran 'very shortly' as officials say progress has been made",
 "鲁比奥希望美伊能“很快”达成霍尔木兹协议 官员称已取得进展",
 "美国国务卿鲁比奥对“很快”与伊朗就霍尔木兹海峡达成协议表示乐观，财长贝森特称协议可能“明天”达成；卡塔尔参与斡旋的谈判据称取得进展。",
 "卫报","地缘政治","鲁比奥,伊朗,霍尔木兹海峡,卡塔尔斡旋",
 "https://www.theguardian.com/world/live/2026/aug/04/middle-east-crisis-qatar-iran-us-israel-war-donald-trump-strait-hormuz-gaza-latest-news-updates",92,True,"美国","2026-08-04"),
("US and Qatar report progress on Iran ceasefire and reopening Hormuz strait",
 "美卡报告伊朗停火及重开霍尔木兹海峡取得进展",
 "美国和卡塔尔报告称，在促成伊朗停火并重开全球关键石油通道霍尔木兹海峡方面取得进展，外交努力在地区紧张背景下持续加码。",
 "卫报","地缘政治","伊朗停火,霍尔木兹海峡,卡塔尔,美国外交",
 "https://www.theguardian.com/world/2026/aug/04/us-qatar-progress-iran-ceasefire-hormuz-strait",88,True,"美国","2026-08-04"),
("Iran's president denies threatening to resign during talks over Strait of Hormuz",
 "伊朗总统否认在霍尔木兹海峡谈判中威胁辞职",
 "伊朗总统否认了关于他在霍尔木兹海峡谈判中威胁辞职的报道，坚称相关传闻不实，谈判仍在继续。",
 "卫报","地缘政治","伊朗总统,辞职传闻,霍尔木兹,谈判",
 "https://www.theguardian.com/world/2026/aug/04/irans-president-denies-threatening-to-resign-during-talks-over-strait-of-hormuz",70,False,"热点","2026-08-04"),
("Yen hits three-month high after Trump helps prop up currency",
 "日元在特朗普支撑汇率后升至三个月高点",
 "在特朗普采取行动支撑日元汇率后，日元兑美元升至三个月高点，反映美日经济互动与汇市波动加剧。",
 "卫报","经济金融","日元,汇率,特朗普,美日关系",
 "https://www.theguardian.com/business/2026/aug/03/yen-trump-currency-us-japan",72,True,"美国","2026-08-03"),
("OpenAI pays $3.2m to settle claims it discriminated against US workers",
 "OpenAI支付320万美元了结歧视美国员工指控",
 "OpenAI同意支付320万美元以了结关于其在招聘和用工中歧视美国员工的指控，AI行业用工合规问题再受关注。",
 "卫报","AI科技","OpenAI,歧视诉讼,和解,用工合规",
 "https://www.theguardian.com/us-news/2026/aug/04/openai-worker-discrimination-claims-settlement",68,False,"美国","2026-08-04"),
("Jerusalem's most important Muslim religious site facing 'imminent' threat of Israeli takeover, says Jordan",
 "约旦称耶路撒冷最重要穆斯林圣地面临以色列接管“迫在眉睫”威胁",
 "约旦就其所称以色列对耶路撒冷阿克萨清真寺“迫在眉睫”的接管威胁召开紧急会议，地区宗教冲突风险再度升温。",
 "卫报","地缘政治","约旦,以色列,耶路撒冷,阿克萨清真寺",
 "https://www.theguardian.com/world/2026/aug/04/jordan-convenes-emergency-meeting-israel-religious-conflict-jerusalem",78,False,"热点","2026-08-04"),
("SpaceX beats revenue expectations in first earnings report after IPO crash",
 "SpaceX在IPO暴跌后首份财报中超出营收预期",
 "SpaceX上市后首份财报营收超预期，尽管股价上市初期大幅下挫，公司财务表现与AI相关收入增长成为市场关注焦点。",
 "卫报","AI科技","SpaceX,财报,IPO,AI收入",
 "https://www.theguardian.com/science/2026/aug/04/spacex-first-earnings-report",70,False,"美国","2026-08-04"),
("EU chief criticises Spain's migrant plan after Ceuta crisis meeting",
 "欧盟领导人批评西班牙移民计划 此前召开休达危机会议",
 "欧盟委员会主席在休达边界危机会议后批评西班牙移民计划，呼吁加强欧盟外部边界与移民管控。",
 "卫报","移民危机","欧盟,西班牙,休达,移民计划",
 "https://www.theguardian.com/world/2026/aug/04/eu-criticises-spain-migrant-plan-ceuta-crisis-meeting",65,False,"欧洲","2026-08-04"),

# ================= CNN =================
("President Trump gives Iran 'last chance' to make a deal",
 "特朗普给伊朗“最后机会”达成协议",
 "视频报道显示，特朗普总统向伊朗发出达成核协议的最后机会，美伊紧张对峙中外交与施压并行。",
 "CNN","地缘政治","特朗普,伊朗,核协议,最后通牒",
 "https://edition.cnn.com/2026/08/04/world/video/president-trump-gives-iran-last-chance-to-make-a-deal-cnc",90,True,"美国","2026-08-04"),
("Drafts of potential US-Iran agreement are 'being circulated,' Qatar says",
 "卡塔尔称美伊潜在协议草案“正在传阅”",
 "卡塔尔表示，一份潜在的美伊协议草案正在各方之间传阅，显示美伊谈判可能出现突破性进展。",
 "CNN","地缘政治","美伊协议,草案,卡塔尔,谈判",
 "https://edition.cnn.com/2026/08/04/world/live-news/iran-war-trump",85,True,"美国","2026-08-04"),
("Japan outlines its military build-up plan, citing threats from China, Russia and North Korea",
 "日本公布军事建设计划 称面临中俄朝威胁",
 "日本发布防卫白皮书，明确以中国、俄罗斯和朝鲜的威胁为由公布军事建设计划，增加防务投入与能力建设。",
 "CNN","地缘政治","日本,防卫白皮书,军事建设,中国威胁",
 "https://edition.cnn.com/2026/08/04/asia/japan-military-white-paper-cite-china-russia-and-north-korea-threat-intl-hnk",82,False,"泛涉华","2026-08-04"),
("White House to meet with top AI companies ahead of first big regulation push",
 "白宫将与顶级AI公司会面 为首次重大监管行动做准备",
 "白宫将召集头部AI公司会面，为首次重大AI监管行动铺路，标志着政府对AI行业正式监管的开端。",
 "CNN","AI科技","白宫,AI监管,科技公司,政策",
 "https://edition.cnn.com/2026/08/03/tech/white-house-meet-with-top-ai-companies-big-regulation-push",80,True,"美国","2026-08-03"),
("AI is giving hackers an edge. Here's how to protect yourself from online scams",
 "AI正让黑客占得先机 如何防范网络诈骗",
 "分析指出，AI正赋予网络犯罪者更复杂的攻击手段，文章就如何防范AI增强型网络诈骗给出实用建议。",
 "CNN","AI科技","AI,网络安全,诈骗,黑客",
 "https://edition.cnn.com/2026/08/04/tech/ai-online-scams-protection",65,False,"美国","2026-08-04"),

# ================= 纽约时报 =================
("A New Lethal Front in Ukraine: Its Beloved Gas Stations",
 "乌克兰的新致命战线：深受喜爱的加油站",
 "俄军无人机袭击了数百个加油站，明显是对乌克兰袭击炼油厂的报复行动，民用基础设施战事再度升级。",
 "纽约时报","俄乌冲突","乌克兰,俄罗斯,加油站,无人机袭击",
 "https://www.nytimes.com/2026/08/04/world/europe/ukraine-gas-stations-russia.html",78,False,"欧洲","2026-08-04"),
("Talks With Iran to Reopen Strait of Hormuz Make Progress, Officials Say",
 "官员称重开霍尔木兹海峡谈判取得进展",
 "卡塔尔称协议草案文本正在传阅，国务卿鲁比奥对谈判表示乐观但强调尚未最终敲定，美伊重开海峡谈判取得阶段性进展。",
 "纽约时报","地缘政治","霍尔木兹海峡,美伊谈判,鲁比奥,卡塔尔",
 "https://www.nytimes.com/2026/08/04/world/middleeast/strait-of-hormuz-deal-progress.html",90,True,"美国","2026-08-04"),
("U.S. Revokes Visa of Top Brazilian Diplomat, Dialing Up Tensions",
 "美国撤销巴西高级外交官签证 紧张升级",
 "美国国务院取消了巴西驻华盛顿大使的签证，两国间外交危机进一步加深。",
 "纽约时报","地缘政治","美国,巴西,大使签证,外交危机",
 "https://www.nytimes.com/2026/08/04/world/americas/brazil-ambassador-us-visa.html",75,False,"美国","2026-08-04"),
("Iran and Oman Hold Talks on Reopening the Strait of Hormuz",
 "伊朗与阿曼就重开霍尔木兹海峡举行会谈",
 "特朗普在周末以谈判取得进展为由取消了威胁中的对伊打击；伊朗则表示目前没有与美国进行谈判。",
 "纽约时报","地缘政治","伊朗,阿曼,霍尔木兹,特朗普",
 "https://www.nytimes.com/2026/08/03/world/middleeast/iran-talks-us-oman-strait-hormuz-trump.html",88,True,"热点","2026-08-03"),
("For Iran, Trump's Reversal on Escalation Shows Who Has the Upper Hand",
 "对伊朗而言，特朗普升级态势的逆转表明谁占上风",
 "专家分析称，伊朗通过扩大地区作战范围向美方发出战争扩大化危险的警告，特朗普取消对伊打击显示双方博弈态势微妙。",
 "纽约时报","地缘政治","伊朗,特朗普,升级,地区战争",
 "https://www.nytimes.com/2026/08/03/world/middleeast/iran-trump-escalation.html",82,True,"热点","2026-08-03"),
("When A.I. Goes Rogue",
 "当AI失控之时",
 "从科幻走进现实：报道探讨AI智能体失控引发的网络安全威胁，以及个人与机构如何应对日益自主化的AI风险。",
 "纽约时报","AI科技","AI失控,智能体,网络安全",
 "https://www.nytimes.com/2026/08/04/world/rogue-ai-agents-cybersecurity-uber.html",80,False,"美国","2026-08-04"),
("Britain's New Leader Announces a Blitz of Change Without a Price Tag",
 "英国新领导人宣布变革风暴 却无价签",
 "英国新首相伯纳姆通过TikTok、播客与承诺掀起变革旋风，一些选民反响积极，但他面临如何为这一切买单的重大抉择。",
 "纽约时报","英国政治","英国,伯纳姆,新政,财政",
 "https://www.nytimes.com/2026/08/04/world/europe/andy-burnham-uk-prime-minister.html",65,False,"欧洲","2026-08-04"),
("Pakistan's Kashmir Problem",
 "巴基斯坦的克什米尔问题",
 "一波抗议浪潮对伊斯兰堡在克什米尔地区的权威构成多年来的最重大挑战。",
 "纽约时报","地缘政治","巴基斯坦,克什米尔,抗议",
 "https://www.nytimes.com/2026/08/04/world/asia/pakistan-kashmir-jaac-rawalkot-protests.html",60,False,"热点","2026-08-04"),

# ================= 华尔街日报 =================
("U.S. Revokes Brazilian Ambassador's Visa Amid Diplomatic Standoff",
 "美国在外交僵局中撤销巴西大使签证",
 "美国在外交对峙中撤销巴西驻美大使的签证，两国关系紧张升级，可能影响美巴外交互动与经贸往来。",
 "华尔街日报","地缘政治","美国,巴西,签证,外交僵局",
 "https://www.wsj.com/politics/policy/u-s-revokes-brazilian-ambassadors-visa-amid-diplomatic-standoff-f7e34200",75,False,"美国","2026-08-04"),
("White House AI Guidelines Exempt U.S. Open Models From Government Review",
 "白宫AI指导方针豁免美国开源模型接受政府审查",
 "白宫发布的人工智能指导方针将美国开源模型排除在政府审查范围之外，该政策在促进创新与引发AI安全担忧之间引发讨论。",
 "华尔街日报","AI科技","白宫,AI监管,开源模型,政府审查",
 "https://www.wsj.com/tech/ai/white-houses-ai-guidelines-exempt-u-s-open-models-from-government-review-74924eb8",82,True,"美国","2026-08-04"),
("SpaceX Says Spending Spree Is Supercharging AI Revenues",
 "SpaceX称支出狂潮正大幅提升AI收入",
 "SpaceX表示大规模资本支出正在加速AI相关收入增长，反映科技巨头竞相布局AI基础设施与算力能力的趋势。",
 "华尔街日报","AI科技","SpaceX,AI收入,资本支出,算力",
 "https://www.wsj.com/tech/ai/spacex-says-spending-spree-is-supercharging-ai-revenues-ea750ff3",70,False,"美国","2026-08-04"),
("OpenAI Calls Apple's Trade-Secret Suit 'Careless' and 'Oddly Personal'",
 "OpenAI称苹果的商业秘密诉讼“草率”且“奇怪地针对个人”",
 "OpenAI对苹果提起的商业秘密诉讼作出强硬回应，两大科技巨头间的法律纠纷反映AI领域激烈的人才与技术竞争。",
 "华尔街日报","AI科技","OpenAI,苹果,商业秘密,诉讼,AI竞争",
 "https://www.wsj.com/tech/openai-calls-apples-trade-secret-suit-careless-and-oddly-personal-a1d290a1",72,False,"美国","2026-08-04"),
("How Trump's Financial Windfall Stiffened Opposition to Landmark Crypto Bill",
 "特朗普的财务收益如何加剧对里程碑式加密货币法案的反对",
 "特朗普因加密货币相关财务收益引发争议，加剧了反对者对里程碑式加密法案的抵制，凸显政商利益与政策立法的复杂交织。",
 "华尔街日报","经济金融","特朗普,加密货币,法案,利益冲突",
 "https://www.wsj.com/politics/policy/how-trumps-financial-windfall-stiffened-opposition-to-landmark-crypto-bill-190582e3",68,True,"美国","2026-08-04"),
("China Chases a Journalist Abroad",
 "中国在海外追查一名记者",
 "社论指出中国在泰国追查记者白兆东，引发对媒体自由与跨境司法管辖权的关注。",
 "华尔街日报","媒体自由","中国,记者,媒体自由,白兆东",
 "https://www.wsj.com/opinion/china-journalist-bai-zhaodong-thailand-communist-party-f47f7262",60,False,"中国","2026-08-04"),

# ================= 半岛电视台 =================
("Diplomatic efforts to reopen Hormuz ramp up as Iran, US signal progress",
 "重开霍尔木兹海峡外交努力升级 伊朗美国均释放进展信号",
 "伊朗称与阿曼的会谈“积极”，美国官员则表示协议可能很快达成，重开霍尔木兹海峡的外交努力明显加码。",
 "半岛电视台","地缘政治","霍尔木兹,伊朗,阿曼,谈判",
 "https://www.aljazeera.com/news/liveblog/2026/8/5/iran-war-live-tehran-oman-talks-on-hormuz-positive-ship-hit-in-red-sea",90,True,"热点","2026-08-05"),
("US revokes visa of Brazilian ambassador amid deepening diplomatic spat",
 "美国在巴西外交争端加深之际撤销巴西大使签证",
 "美国撤销了巴西驻美大使的签证，两国不断加深的外交摩擦再度升级。",
 "半岛电视台","地缘政治","美国,巴西,签证,外交摩擦",
 "https://www.aljazeera.com/news/2026/8/4/us-revokes-visa-of-brazilian-ambassador-amid-deepening-diplomatic-spat",75,False,"美国","2026-08-04"),
("One killed, five injured in Russian ballistic missile attack on Kyiv",
 "俄军弹道导弹袭击基辅致1死5伤",
 "俄军弹道导弹袭击乌克兰首都基辅，造成1人死亡、5人受伤，城市基础设施受损。",
 "半岛电视台","俄乌冲突","俄罗斯,基辅,弹道导弹",
 "https://www.aljazeera.com/news/2026/8/4/russia-strikes-ukrainian-capital-kyiv-with-ballistic-missiles",80,False,"欧洲","2026-08-04"),
("US says deal on reopening Hormuz close as Iran, Oman hold 'positive' talks",
 "美国称重开霍尔木兹协议接近达成 伊朗阿曼会谈“积极”",
 "美国表示重开霍尔木兹海峡的协议接近达成，与此同时伊朗与阿曼举行了“积极”的会谈。",
 "半岛电视台","地缘政治","霍尔木兹,美伊,阿曼,协议",
 "https://www.aljazeera.com/news/2026/8/4/us-says-deal-on-reopening-hormuz-close-as-iran-oman-hold-positive-talks",88,True,"美国","2026-08-04"),
("White House to meet AI firms on advanced model safety",
 "白宫将与AI公司会面讨论先进模型安全",
 "白宫确认将于周二召开会议讨论先进AI模型安全问题，近期发生的一系列高调黑客事件推动议程加速。",
 "半岛电视台","AI科技","白宫,AI安全,先进模型,黑客事件",
 "https://www.aljazeera.com/economy/2026/8/4/white-house-to-meet-ai-firms-on-advanced-model-safety",80,True,"美国","2026-08-04"),
("'Maximum use': Iran boosts military strength during ceasefire with US",
 "伊朗在美伊停火期间增强军力",
 "伊朗革命卫队发言人上月表示，伊朗在停火期间提高了导弹生产速度，“最大化利用”窗口期强化军力。",
 "半岛电视台","军事国防","伊朗,革命卫队,导弹,停火",
 "https://www.aljazeera.com/news/2026/8/4/maximum-use-iran-boosts-military-strength-during-ceasefire-with-us",72,False,"热点","2026-08-04"),
("National Guard deployment to Washington, DC, will cost US roughly $1.4bn",
 "国民警卫队部署华盛顿将耗资约14亿美元",
 "美国国民警卫队部署至华盛顿的军事行动预计花费约14亿美元，成为一项重大财政支出。",
 "半岛电视台","美国政治","国民警卫队,华盛顿,军费",
 "https://www.aljazeera.com/news/2026/8/4/national-guard-deployment-to-washington-dc-will-cost-us-roughly-1-4bn",62,False,"美国","2026-08-04"),
("US court deals blow to Trump's bid to scrap climate grant programme",
 "美国法院打击特朗普废除气候拨款计划的努力",
 "美国法院作出不利于特朗普政府废除气候拨款计划的裁决，政府气候政策议程遭遇司法阻力。",
 "半岛电视台","美国政治","美国法院,特朗普,气候拨款,司法裁决",
 "https://www.aljazeera.com/news/2026/8/4/us-court-deals-blow-to-trumps-bid-to-scrap-climate-grant-programme",65,True,"美国","2026-08-04"),
("Argentina grain exports halt as maritime pilots strike over Milei decree",
 "阿根廷谷物出口因海事领航员罢工而停滞",
 "受米莱政府法令引发的海事领航员罢工影响，阿根廷港口超45艘货轮受影响，谷物出口陷入停滞。",
 "半岛电视台","经济金融","阿根廷,谷物出口,罢工,米莱",
 "https://www.aljazeera.com/news/2026/8/4/argentina-grain-exports-halt-as-maritime-pilots-strike-over-milei-decree",62,False,"热点","2026-08-04"),

# ================= Politico =================
("White House AI vetting plan to exempt lower-cost 'open' models",
 "白宫AI审查计划拟豁免低成本“开源”模型",
 "白宫已敲定AI监管框架，将豁免非专有的低成本AI模型接受政府审查，意在国家安全与开源AI创新之间取得平衡。",
 "Politico","AI科技","白宫,AI审查,开源模型,国家安全",
 "https://www.politico.com/news/2026/08/04/white-house-ai-vetting-plan-to-exempt-nonproprietary-models-01024816",82,True,"美国","2026-08-04"),
("White House finalizes artificial intelligence oversight framework",
 "白宫最终敲定人工智能监管框架",
 "政府完成自愿性AI监管框架，为先进AI系统的政府审查确立准则，框架强调行业合作并保留未来强制要求的空间。",
 "Politico","AI科技","白宫,AI监管框架,科技政策",
 "https://www.politico.com/news/2026/08/03/white-house-finalizes-voluntary-ai-oversight-framework-01022437",80,True,"美国","2026-08-03"),
("Democratic-led states sue to block Trump's latest wave of tariffs",
 "民主党主导的州起诉阻止特朗普最新一轮关税",
 "一批民主党主导的州联合提起诉讼，挑战政府最新一轮进口关税，指其超出总统权限并损害州经济。",
 "Politico","经贸制裁","关税,诉讼,民主党,贸易政策",
 "https://www.politico.com/news/2026/08/03/democratic-states-trump-tariffs-01023161",78,True,"美国","2026-08-03"),
("Trump has been able to keep oil prices low. But that power may not last forever.",
 "特朗普一直能压低油价 但这种能力可能不会持久",
 "政府压低油价的努力迄今奏效，但分析人士警告地缘政治紧张与炼能限制可能削弱这一杠杆，能源价格稳定的脆弱性显现。",
 "Politico","经济金融","油价,能源政策,地缘政治,炼能",
 "https://www.politico.com/news/2026/08/03/trump-gas-oil-prices-iran-01022998",70,True,"美国","2026-08-03"),
("US sends more intel assets to Cuba",
 "美国向古巴增派情报资产",
 "在地区安全关切上升的背景下，美国向古巴增派更多情报资源，显示对加勒比地区地缘战略关注加深。",
 "Politico","地缘政治","美国,古巴,情报,加勒比",
 "https://www.politico.com/news/2026/08/04/us-sends-more-intel-assets-to-cuba-01023267",62,False,"美国","2026-08-04"),
("Europe wants to kick its Palantir habit",
 "欧洲想戒掉对Palantir的依赖",
 "欧洲多国政府正寻求替代Palantir数据分析软件的方案，出于对美方数据访问与技术主权的担忧，推动本土防务科技发展。",
 "Politico","科技主权","欧洲,Palantir,数据主权,防务科技",
 "https://www.politico.eu/article/europe-wants-to-kick-its-palantir-habit/",70,False,"欧洲","2026-08-04"),
("Louisiana wants a space port. Building it could get much easier.",
 "路易斯安那州想建航天港 建设或将更加容易",
 "拟议的监管调整或简化商业航天港审批流程，利好路易斯安那州建设大型发射设施的计划。",
 "Politico","科技产业","航天港,商业航天,监管,路易斯安那",
 "https://www.politico.com/news/2026/08/04/louisiana-rockets-regulation-changes-01023711",55,False,"美国","2026-08-04"),

# ================= 华盛顿邮报 =================
("Trump keeps making threats. The world has stopped flinching.",
 "特朗普不断发出威胁 世界却已不再退缩",
 "总统的强硬言论已不再让世界领导人感到震慑——他们看到他受制于法院、被国会驳回、被伊朗拖延，威胁外交的效力正在下降。",
 "华盛顿邮报","地缘政治","特朗普,威胁外交,国际反应",
 "https://www.washingtonpost.com/world/2026/08/04/trump-keeps-making-threats-washington-world-have-stopped-flinching/",82,True,"美国","2026-08-04"),
("Iran rejects Trump's claim that talks will restart, adding to weekend of whiplash",
 "伊朗否认特朗普关于谈判重启的说法 周末局势反复",
 "伊朗拒绝接受特朗普所称谈判将重启的说法，为周末本就反复的美伊局势再添变数。",
 "华盛顿邮报","地缘政治","伊朗,特朗普,谈判,局势反复",
 "https://www.washingtonpost.com/world/2026/08/02/trump-cancels-iran-attack-citing-progress-deal-tehran-israel-alert/",85,True,"美国","2026-08-03"),
("Labour overtakes Trump-aligned Reform UK in national polls",
 "工党民调反超特朗普结盟的英国改革党",
 "英国新首相伯纳姆领导的工党一年多来首次在全国民调中反超与特朗普结盟、反移民的英国改革党。",
 "华盛顿邮报","英国政治","工党,伯纳姆,改革党,民调",
 "https://www.washingtonpost.com/world/2026/08/03/labour-overtakes-reform-uk-national-polls/",68,False,"欧洲","2026-08-03"),
("Boris Nadezhdin, anti-war candidate in Russia, flees to France",
 "俄罗斯反战候选人纳杰日金逃往法国",
 "被禁止参加9月议会选举的俄罗斯反战候选人纳杰日金已逃往法国，他在巴黎发布视频称“我还活着，并且自由”。",
 "华盛顿邮报","地缘政治","俄罗斯,纳杰日金,反战,流亡",
 "https://www.washingtonpost.com/world/2026/08/03/boris-nadezhdin-anti-war-candidate-russia-flees-france/",70,False,"欧洲","2026-08-03"),
("After months on the Iran war's sidelines, Yemen's Houthis open a dangerous new front",
 "胡塞武装为伊朗战争开辟危险新战线",
 "德黑兰支持的胡塞武装封锁沙特船只，为地区安全再添一条关键水道风险，伊朗战争的外溢效应扩大。",
 "华盛顿邮报","地缘政治","胡塞武装,沙特,伊朗战争,红海",
 "https://www.washingtonpost.com/world/2026/08/02/strikes-against-saudi-arabia-by-yemens-houthis-widen-dangers-iran-war/",78,False,"热点","2026-08-02"),
("Loomer's Ukraine reversal deepens split in Trump's 'America First' movement",
 "卢默的乌克兰立场反转加深特朗普“美国优先”阵营分裂",
 "有影响力的MAGA博主、前基辅批评者劳拉·卢默预计将访见总统，为其主张的美乌联盟立场辩护，阵营内部分歧加深。",
 "华盛顿邮报","美国政治","卢默,特朗普,乌克兰,美国优先",
 "https://www.washingtonpost.com/politics/2026/08/02/inside-laura-loomer-surprising-turn-ukraine/",65,True,"美国","2026-08-03"),
("ICE begins outfitting Haitian immigrants with ankle monitors, attorneys say",
 "律师称ICE开始为海地移民佩戴脚踝监控器",
 "美国移民海关执法局开始为部分海地移民佩戴脚踝监控装置，围绕约35万海地人受保护身份的争议持续发酵。",
 "华盛顿邮报","移民危机","ICE,海地移民,脚踝监控,移民政策",
 "https://www.washingtonpost.com/immigration/2026/08/03/ice-begins-outfitting-haitian-immigrants-with-ankle-monitors-attorneys-say/",60,False,"美国","2026-08-03"),
("Deported by the U.S., detained in Venezuela — then lost in the earthquakes",
 "被美国遣返、在委内瑞拉被拘留——随后在地震中失踪",
 "乘坐164航班的移民原本在美国追求生活，被ICE拘留后遣返委内瑞拉，却在一座数小时后坍塌的建筑中被扣押，命运令人唏嘘。",
 "华盛顿邮报","移民危机","委内瑞拉,遣返,地震,ICE",
 "https://www.washingtonpost.com/immigration/interactive/2026/08/02/deported-by-trump-detained-venezuela-then-lost-earthquakes/",65,False,"热点","2026-08-02"),

# ================= 美联社 =================
("Iran and Oman make progress on a deal to reopen the Strait of Hormuz, officials say",
 "官员称伊朗与阿曼就重开霍尔木兹海峡达成协议取得进展",
 "官员表示，伊朗与阿曼正就重开霍尔木兹海峡制定方案并取得进展，这一全球最关键的石油运输通道之一有望恢复通航。",
 "美联社","地缘政治","伊朗,阿曼,霍尔木兹海峡,外交",
 "https://apnews.com/article/iran-us-war-strait-hormuz-oman-diplomacy-6587f90f2ab5beec373ce5fabf637541",88,False,"热点","2026-08-04"),
("Netanyahu says no Israeli withdrawal from Gaza until Hamas has been completely disarmed",
 "内塔尼亚胡称哈马斯完全解除武装前以色列不会从加沙撤军",
 "以色列总理内塔尼亚胡表示，在哈马斯完全解除武装之前，以色列不会从加沙现有战线撤军；加沙局势与停火谈判继续胶着。",
 "美联社","地缘政治","内塔尼亚胡,以色列,加沙,哈马斯,停火",
 "https://apnews.com/article/israel-palestinians-hamas-war-gaza-news-1215e52022856b9de9837237a0e188fa",78,True,"热点","2026-08-04"),
("Elon Musk's xAI sues Minnesota over its first-in-the-nation law banning 'nudification' technology",
 "马斯克旗下xAI起诉明尼苏达州 针对全国首创的“深度伪造换脸”禁令",
 "马斯克旗下AI公司xAI起诉明尼苏达州，针对该州全国首创的禁止用AI制作未经同意色情图像的“换脸”技术法律，案件涉及AI创新与监管边界。",
 "美联社","AI科技","xAI,马斯克,明尼苏达,深度伪造,AI监管",
 "https://apnews.com/article/minnesota-artificial-intelligence-nudification-x-elon-musk-deepfake-131184be939d540de093b567b12c9e16",72,False,"美国","2026-08-04"),
("US stocks hit records as profits keep piling up for Palantir and others, while oil prices ease",
 "美股创历史新高 Palantir等利润攀升 油价回落",
 "美国股市创历史新高，Palantir等公司利润持续增长，同时油价在伊朗战争局势发展下回落，市场在风险中保持强势。",
 "美联社","经济金融","美股,历史新高,Palantir,油价",
 "https://apnews.com/article/stocks-markets-dollar-yen-trump-iran-war-fbbe6128d618509e33d45a493c2615b1",65,False,"美国","2026-08-04"),
("China's Tibet autonomous region showcases elderly care and ethnic unity to foreign journalists",
 "中国西藏自治区向外媒记者展示养老服务和民族团结",
 "在政府组织的外媒记者参访中，西藏城关区老年人日间照料中心的老人展示了太极等活动，活动与民族团结法规相关，并涉及达赖喇嘛议题的持续国际关注。",
 "美联社","中国社会","西藏,养老,民族团结,外媒",
 "https://apnews.com/article/china-tibet-ethnic-unity-law-dalai-lama-7b65b56e0be7307175f429c97a81b93e",68,False,"中国","2026-08-04"),
]

rows = []
for (te, tz, sm, src, cat, kw, url, score, summit, col, date) in items:
    rows.append({
        "title": f"{te} {tz}",
        "title_en": te,
        "summary": sm,
        "source": src,
        "category": cat,
        "keywords": kw,
        "url": url,
        "priority_score": score,
        "is_summit_level": summit,
        "column": col,
        "date": date,
    })

# URL 完整性校验
bad = [r for r in rows if not (r['url'] or '').startswith('https://')]
print(f"组装 {len(rows)} 条 | 缺URL {len(bad)}")
if bad:
    for r in bad: print('  BAD:', r['title_en'][:60])

# 去重（按 title_en[:40]）
seen, dedup = set(), []
for r in rows:
    k = r['title_en'][:40]
    if k not in seen:
        seen.add(k)
        dedup.append(r)
print(f"去重后 {len(dedup)} 条")

with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(dedup, f, ensure_ascii=False, indent=2)
print(f"已写入 {OUT}")
