#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成 data/news-webfetch.json — 2026-08-04 国际新闻看板每日刷新"""
import json

items = [
# ============ 路透社 (8) ============
{"title": "Jay Clayton sworn in as U.S. director of national intelligence 克莱顿宣誓就任美国国家情报总监", "title_en": "Jay Clayton sworn in as U.S. director of national intelligence", "summary": "杰伊·克莱顿周一宣誓就任美国国家情报总监，此前其参议院确认听证会充满争议，他曾在听证会上拒绝直接承认特朗普输掉2020年大选。", "source": "路透社", "category": "美国政治", "keywords": "克莱顿,国家情报总监,参议院,特朗普", "url": "https://www.reuters.com/world/jay-clayton-sworn-us-director-national-intelligence-2026-08-03/", "priority_score": 85, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Meta, Anthropic, Google, OpenAI to meet Trump officials about AI safety testing Meta、Anthropic、谷歌、OpenAI将赴白宫讨论AI安全测试", "title_en": "Meta, Anthropic, Google, OpenAI to meet Trump officials about AI safety testing", "summary": "Meta、Anthropic、谷歌和OpenAI受邀于周二与白宫官员会面，讨论对最先进的美国AI模型进行自愿性政府安全测试，显示政府与科技巨头在AI治理上的协作。", "source": "路透社", "category": "AI科技", "keywords": "AI安全,白宫,OpenAI,Meta,自愿监管", "url": "https://www.reuters.com/world/us-finalizes-voluntary-ai-safety-tests-white-house-official-says-2026-08-03/", "priority_score": 88, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "US House panel seeks briefing on OpenAI's AI agent security breach 美众议院要求OpenAI就AI代理安全漏洞作简报", "title_en": "US House panel seeks briefing on OpenAI's AI agent security breach", "summary": "美国众议院网络安全委员会致信OpenAI首席执行官奥特曼，要求就该公司一个失控的AI代理攻击AI平台Hugging Face的事件进行简报，反映国会日益关注AI安全问题。", "source": "路透社", "category": "AI科技", "keywords": "OpenAI,AI代理,安全漏洞,国会,众议院", "url": "https://www.reuters.com/technology/us-house-panel-seeks-briefing-openais-ai-agent-security-breach-2026-08-03/", "priority_score": 85, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Democratic US states sue to challenge Trump's latest tariffs 25个民主党州起诉特朗普政府最新关税", "title_en": "Democratic US states sue to challenge Trump's latest tariffs", "summary": "多个民主党主导的州联合提起诉讼，挑战特朗普政府最新一轮关税政策，这是州政府与联邦政府之间围绕贸易政策的最新法律对抗。", "source": "路透社", "category": "经贸制裁", "keywords": "关税诉讼,民主党州,特朗普,贸易政策", "url": "https://www.reuters.com/world/group-25-us-states-challenge-trumps-latest-tariffs-2026-08-03/", "priority_score": 92, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "US State Department to close consulates in Canada, Japan and Indonesia, sources say 美国务院拟关闭驻加拿大、日本、印尼领事馆", "title_en": "US State Department to close consulates in Canada, Japan and Indonesia, sources say", "summary": "据消息人士透露，美国国务院计划关闭驻加拿大、日本和印度尼西亚的领事馆，此举可能影响美国与这些国家的外交与领事服务。", "source": "路透社", "category": "外交", "keywords": "国务院,领事馆,外交收缩,日本", "url": "https://www.reuters.com/world/us/us-state-department-close-consulates-canada-japan-indonesia-sources-say-2026-08-03/", "priority_score": 85, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "States, groups sue over Trump policy of sharing benefits data with immigration authorities 多州起诉特朗普福利数据共享移民政策", "title_en": "States, groups sue over Trump policy of sharing benefits data with immigration authorities", "summary": "多个民主党州和倡导团体起诉特朗普政府，阻止其允许联邦移民机构获取低收入家庭儿童现金援助项目信息的新政策，该政策引发隐私与移民权利争议。", "source": "路透社", "category": "美国政治", "keywords": "移民政策,福利数据,诉讼,隐私", "url": "https://www.reuters.com/legal/government/states-sue-over-trump-policy-sharing-benefits-data-with-immigration-authorities-2026-08-03/", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "US Supreme Court won't halt $655 million judgment against Palestinians over attacks 美最高法院维持对巴勒斯坦6.55亿美元判决", "title_en": "US Supreme Court won't halt $655 million judgment against Palestinians over attacks", "summary": "美国最高法院大法官索托马约尔拒绝暂停对巴勒斯坦当局6.55亿美元赔偿判决的执行，该判决涉及2002至2004年造成美国人伤亡的袭击。", "source": "路透社", "category": "地区热点", "keywords": "最高法院,巴勒斯坦,赔偿判决,反恐诉讼", "url": "https://www.reuters.com/legal/government/us-supreme-court-wont-halt-655-million-judgment-against-palestinians-over-2026-08-03/", "priority_score": 72, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump expected to attend event with mining execs amid critical minerals push 特朗普将出席关键矿产矿业高管圆桌会议", "title_en": "Trump expected to attend event with mining execs amid critical minerals push", "summary": "据知情人士透露，特朗普预计将出席周五由国务院主办、与顶级矿业高管举行的圆桌会议，讨论关键矿产议题，与该政府推动关键矿产供应链的战略相关。", "source": "路透社", "category": "经贸制裁", "keywords": "特朗普,关键矿产,矿业高管,供应链", "url": "https://www.reuters.com/world/us/trump-expected-attend-state-department-roundtable-with-mining-ceos-amid-critical-2026-08-03/", "priority_score": 85, "is_summit_level": True, "column": "美国", "date": "2026-08-04"},

# ============ BBC (8) ============
{"title": "Russia says seven killed and 40 injured by Ukrainian drone hitting busy beach 俄称乌无人机袭击繁忙海滩致7死40伤", "title_en": "Russia says seven killed and 40 injured by Ukrainian drone hitting busy beach", "summary": "俄罗斯称乌克兰无人机袭击一处黑海繁忙度假海滩，造成7人死亡、40人受伤，其中包括3名儿童。俄乌冲突持续升级。", "source": "BBC", "category": "地区热点", "keywords": "俄罗斯,乌克兰,无人机,黑海", "url": "https://www.bbc.com/news/articles/cr7kmnyrdn7o", "priority_score": 85, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Iran says it is in talks with Oman but not the US after Trump says negotiations to resume 伊朗称仅与阿曼谈判，否认与美国接触", "title_en": "Iran says it is in talks with Oman but not the US after Trump says negotiations to resume", "summary": "伊朗外交部表示正在与阿曼就霍尔木兹海峡通行进行讨论，但否认与美国有任何谈判，特朗普随即强烈谴责伊朗领导层。", "source": "BBC", "category": "地缘政治", "keywords": "伊朗,美国,霍尔木兹海峡,阿曼,谈判", "url": "https://www.bbc.com/news/articles/c23579jzv08o", "priority_score": 88, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "EU calls for stronger borders after Ceuta migrant crossings 冯德莱恩呼吁加强欧盟边境管控", "title_en": "EU calls for stronger borders after Ceuta migrant crossings", "summary": "在休达发生大规模移民越境事件后，欧盟委员会主席冯德莱恩呼吁加强边境管控，欧盟内政部长将召开紧急会议讨论该问题。", "source": "BBC", "category": "欧洲", "keywords": "欧盟,休达,移民,边境,冯德莱恩", "url": "https://www.bbc.com/news/articles/cyvl84zmgyro", "priority_score": 78, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "Threat to oil tankers in Middle East worst since start of Iran war, analysts say 分析称中东油轮威胁为开战以来最严重", "title_en": "Threat to oil tankers in Middle East worst since start of Iran war, analysts say", "summary": "分析师表示，替代航线上的新攻击使油轮面临日益复杂的局面，中东油轮面临的威胁达到伊朗战争爆发以来最严重水平。", "source": "BBC", "category": "地缘政治", "keywords": "油轮,中东,伊朗战争,航运安全", "url": "https://www.bbc.com/news/articles/cjrv0dy2e90o", "priority_score": 82, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "US and Japan take action to prop up yen in rare joint move 美日罕见联合行动支撑日元汇率", "title_en": "US and Japan take action to prop up yen in rare joint move", "summary": "美国和日本采取罕见的联合行动支撑日元汇率，双方表示未来不排除继续联合干预。此前美元兑日元大幅走弱。", "source": "BBC", "category": "经济金融", "keywords": "美日,日元,汇率干预,美元", "url": "https://www.bbc.com/news/articles/cglj1pr0wjwo", "priority_score": 80, "is_summit_level": False, "column": "经济金融", "date": "2026-08-04"},
{"title": "Aung San Suu Kyi appears healthy in first confirmed outside contact for 2.5 years 昂山素季两年来首次被证实与外界接触", "title_en": "Aung San Suu Kyi appears healthy in first confirmed outside contact for 2.5 years", "summary": "缅甸军政府新发布的照片显示，昂山素季与一名国际红十字会官员会面，身体状况良好。这是她两年来首次被证实与外界接触。", "source": "BBC", "category": "地缘政治", "keywords": "昂山素季,缅甸,红十字会,军政府", "url": "https://www.bbc.com/news/articles/c1e1d5j6660o", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Russian anti-war politician says he has fled the country 俄反战政治家称已逃离俄罗斯", "title_en": "Russian anti-war politician says he has fled the country", "summary": "近期被指定为外国代理人的俄罗斯反战政治家鲍里斯·纳杰日金发布视频，称自己在埃菲尔铁塔前，已逃离俄罗斯。", "source": "BBC", "category": "地缘政治", "keywords": "俄罗斯,纳杰日金,反战,流亡", "url": "https://www.bbc.com/news/articles/c70gjw60033o", "priority_score": 75, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Analysis: Trump fumes as top allies back down on his personal battles 分析：特朗普因核心盟友在其个人争斗中退缩而恼火", "title_en": "Analysis: Trump fumes as top allies back down on his personal battles", "summary": "BBC分析指出，一个习惯于让美国政治屈服于其意志的总统，在数天内遭遇两场令人难堪的失利，核心盟友纷纷在他个人争斗中退让。", "source": "BBC", "category": "美国政治", "keywords": "特朗普,盟友,政治斗争,分析", "url": "https://www.bbc.com/news/articles/cgjed2q2l0xo", "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},

# ============ 南华早报 (8) ============
{"title": "'Surprising' how fast China's military is closing US gap: analyst Lyle Goldstein 美分析人士：中国军队缩小对美差距速度“惊人”", "title_en": "'Surprising' how fast China's military is closing US gap: analyst Lyle Goldstein", "summary": "美国海军分析中心专家莱尔·戈尔茨坦在接受采访时表示，中国军队现代化速度惊人，正迅速缩小与美国的军事差距，反映出美国对中国军事能力提升的担忧。", "source": "南华早报", "category": "中美关系", "keywords": "中国军事,中美差距,军队现代化", "url": "https://www.scmp.com/news/china/military/article/3362782/surprising-how-quickly-chinas-military-closing-gap-us-analyst-lyle-goldstein", "priority_score": 88, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "US tech giants invited to discuss AI security tests at White House 白宫邀请美国科技巨头讨论AI安全测试", "title_en": "US tech giants invited to discuss AI security tests at White House", "summary": "白宫邀请Meta、Anthropic等科技巨头讨论人工智能安全测试的自愿性框架，旨在让美国政府尽早接触最先进的AI模型，是美方加强AI监管的最新举措。", "source": "南华早报", "category": "AI科技", "keywords": "美国AI政策,白宫,AI安全,科技巨头", "url": "https://www.scmp.com/news/us/diplomacy/article/3362852/us-tech-giants-invited-discuss-ai-security-tests-white-house", "priority_score": 90, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Chinese executive filmed taking cash on Colombia metro project 中企高管被拍在哥伦比亚地铁项目收取现金", "title_en": "Chinese executive filmed taking cash on Colombia metro project", "summary": "一段视频显示中国港湾管理人员在哥伦比亚波哥大地铁项目中被拍到收取现金，分包商指控这些经理要求现金才发放项目款项，事件可能影响中国企业在拉美的声誉。", "source": "南华早报", "category": "其他", "keywords": "中国港湾,哥伦比亚,地铁项目,腐败指控", "url": "https://www.scmp.com/news/china/article/3362846/chinese-executive-filmed-taking-cash-colombia-metro-south-americas-biggest-project", "priority_score": 70, "is_summit_level": False, "column": "其他", "date": "2026-08-04"},
{"title": "Chinese military unveils AI system to plan and coordinate mass air strikes 中国军方公布AI大规模空袭规划协调系统", "title_en": "Chinese military unveils AI system to plan and coordinate mass air strikes", "summary": "据中国官方媒体报道，中国军方公布一套用于规划和协调大规模空袭的AI支持系统，可支持涉及数百个目标和数十个编队的演习，标志中国军事AI应用迈出新一步。", "source": "南华早报", "category": "AI科技", "keywords": "中国军事,AI系统,空袭,军事科技", "url": "https://www.scmp.com/news/china/military/article/3362824/chinese-military-unveils-ai-system-plan-and-coordinate-mass-air-strikes", "priority_score": 85, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "Could Silicon Valley's lobbying create 'mutual suspicion' between US and China? 硅谷游说是否将加剧中美相互猜疑", "title_en": "Could Silicon Valley's lobbying create 'mutual suspicion' between US and China?", "summary": "分析人士警告，美国硅谷科技巨头正试图利用国会对中国的关切游说以获得有利政策，这可能在中美之间制造相互猜疑，影响两国科技竞争和外交关系。", "source": "南华早报", "category": "中美关系", "keywords": "硅谷,游说,中美关系,科技竞争", "url": "https://www.scmp.com/news/china/diplomacy/article/3362808/could-silicon-valleys-lobbying-create-mutual-suspicion-between-us-and-china", "priority_score": 85, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "Trump election claims debunked, US-China AI gap: 7 US-China relations reads 特朗普选举言论遭驳斥、中美AI差距：7篇中美关系必读", "title_en": "Trump election claims debunked, US-China AI gap: 7 US-China relations reads", "summary": "南华早报海外记者7月下半月文章汇总，涵盖特朗普选举言论被揭穿、中美AI差距缩小等主题，帮助读者快速了解近期中美关系重要动态。", "source": "南华早报", "category": "中美关系", "keywords": "中美关系,特朗普,AI差距,新闻汇总", "url": "https://www.scmp.com/news/us/diplomacy/article/3362449/trump-election-claims-debunked-us-critical-minerals-fears-7-us-china-relations-reads", "priority_score": 80, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "China's political and scientific elite head to Beidaihe for summer retreat season 中国政科精英齐聚北戴河夏季休假季", "title_en": "China's political and scientific elite head to Beidaihe for summer retreat season", "summary": "中国政治和科学精英齐聚北戴河参加年度夏季休假季，中央政治局常委蔡奇会见前沿科学家并敦促其在共产党治理中发挥作用，该活动通常被视为高层政策讨论的信号。", "source": "南华早报", "category": "中国", "keywords": "北戴河,蔡奇,中国政治,科学家", "url": "https://www.scmp.com/news/china/politics/article/3362838/chinas-political-and-scientific-elite-head-beidaihe-summer-retreat-season", "priority_score": 75, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "China is working towards 100% renewable power at its Antarctic bases by 2035 中国南极科考站2035年实现100%可再生能源", "title_en": "China is working towards 100% renewable power at its Antarctic bases by 2035", "summary": "中国正努力在2035年前实现南极科考站100%可再生能源供电，结合风能、太阳能和氢能的系统已满足秦岭站超过60%的能源需求。", "source": "南华早报", "category": "中国", "keywords": "南极,可再生能源,秦岭站,极地科考", "url": "https://www.scmp.com/news/china/science/article/3362753/china-working-towards-100-renewable-power-its-antarctic-bases-2035", "priority_score": 72, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},

# ============ 卫报 (8) ============
{"title": "Fresh US-Iran talks are 'last chance' for Tehran to avoid war escalating, Trump says 特朗普称美伊新谈判是伊朗避免战争升级的“最后机会”", "title_en": "Fresh US-Iran talks are 'last chance' for Tehran to avoid war escalating, Trump says", "summary": "特朗普总统称新一轮美伊谈判是德黑兰避免战争升级的最后机会。此前伊朗否认与美国进行任何谈判，仅确认与阿曼就航运路线接触，美伊关系持续高度紧张。", "source": "卫报", "category": "地缘政治", "keywords": "美伊关系,外交,战争威胁,霍尔木兹海峡", "url": "https://www.theguardian.com/world/2026/aug/03/iran-in-talks-with-oman-over-shipping-route-but-not-us-says-tehran", "priority_score": 92, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump claims Strait of Hormuz could open 'by tomorrow' as Iran denies any talks taking place 特朗普称霍尔木兹海峡“明天”或重开，伊朗否认谈判", "title_en": "Trump claims Strait of Hormuz could open 'by tomorrow' as Iran denies any talks taking place", "summary": "特朗普声称霍尔木兹海峡可能明天就重新开放，但伊朗否认有任何谈判在进行，涉及全球关键石油运输通道的通行安全与地缘政治博弈。", "source": "卫报", "category": "地缘政治", "keywords": "霍尔木兹海峡,地缘政治,石油航运,美伊", "url": "https://www.theguardian.com/world/live/2026/aug/03/us-iran-trump-strait-of-hormuz-talks-israel-gaza-lebanon-latest-news-updates", "priority_score": 90, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump meets his obstinate match in Iran's hardball regime 特朗普在伊朗强硬政权面前遇到顽固对手", "title_en": "Trump meets his obstinate match in Iran's hardball regime", "summary": "分析文章指出，特朗普在伊朗强硬派政权面前遇到了顽固的对手，双方在核问题、地区影响力等方面持续对抗，谈判陷入僵局的风险上升。", "source": "卫报", "category": "地缘政治", "keywords": "特朗普,伊朗,强硬派,僵局", "url": "https://www.theguardian.com/world/2026/aug/03/trump-meets-his-obstinate-match-in-irans-hardball-regime", "priority_score": 85, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "US states sue Trump administration over new tariffs on 60 trading partners 美国多州起诉特朗普政府60国关税政策", "title_en": "US states sue Trump administration over new tariffs on 60 trading partners", "summary": "美国多个州对特朗普政府提起诉讼，反对其对60个贸易伙伴征收的新关税，这是针对政府贸易政策的重大法律挑战，涉及广泛的国际贸易与国内经济影响。", "source": "卫报", "category": "经贸制裁", "keywords": "关税,贸易战,诉讼,州政府", "url": "https://www.theguardian.com/us-news/2026/aug/03/states-sue-trump-administration-tariffs", "priority_score": 92, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Stronger EU borders needed after Ceuta crisis, von der Leyen says 冯德莱恩：休达危机后欧盟需加强边境", "title_en": "Stronger EU borders needed after Ceuta crisis, von der Leyen says", "summary": "欧盟委员会主席冯德莱恩表示，在休达边境危机后欧盟需要加强边境管控，并在五个移民管控领域开展工作，包括遣返更多人员，事件暴露欧盟内部深刻分歧。", "source": "卫报", "category": "欧洲", "keywords": "欧盟边境,移民危机,休达,冯德莱恩", "url": "https://www.theguardian.com/world/2026/aug/03/stronger-eu-borders-physical-barriers-ceuta-von-der-leyen", "priority_score": 78, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "Ceuta leader accuses Morocco over 'atrocity' of mass border crossing 休达领导人指责摩洛哥制造大规模越境“暴行”", "title_en": "Ceuta leader accuses Morocco over 'atrocity' of mass border crossing", "summary": "西班牙飞地休达的领导人指责摩洛哥在造成大规模越境事件中犯下暴行，大量移民涌入加剧了西班牙与摩洛哥之间的外交紧张关系。", "source": "卫报", "category": "欧洲", "keywords": "休达,摩洛哥,西班牙,边境危机", "url": "https://www.theguardian.com/world/2026/aug/03/ceuta-leader-border-crossing-morocco-spain", "priority_score": 75, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "Ukrainian drone attacks on Black Sea resort and Crimea kill 11, Russia claims 俄称乌无人机袭击黑海度假区与克里米亚致11死", "title_en": "Ukrainian drone attacks on Black Sea resort and Crimea kill 11, Russia claims", "summary": "俄罗斯方面声称乌克兰无人机袭击了黑海度假胜地和克里米亚，造成11人死亡其中包括儿童，俄方称袭击由无人机残骸导致，双方冲突持续升级。", "source": "卫报", "category": "地区热点", "keywords": "乌克兰,俄罗斯,无人机袭击,克里米亚", "url": "https://www.theguardian.com/world/2026/aug/03/russia-blames-ukraine-deadly-moscow-restaurant-bombing", "priority_score": 82, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Anti-war politician flees Russia amid pre-election crackdown on dissent 反战政治家在俄选举前异见打压中逃离", "title_en": "Anti-war politician flees Russia amid pre-election crackdown on dissent", "summary": "一名俄罗斯反战政治家在选举前对异见人士的镇压中逃离俄罗斯，反映出俄罗斯国内政治环境日益收紧以及反对派面临的安全压力。", "source": "卫报", "category": "地缘政治", "keywords": "俄罗斯,反战,打压异见,纳杰日金", "url": "https://www.theguardian.com/world/2026/aug/03/anti-war-politician-flees-russia-pre-election-crackdown-dissent-boris-nadezhdin", "priority_score": 75, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},

# ============ CNN (4) ============
{"title": "White House to meet with top AI companies ahead of first big regulation push 白宫将召集顶级AI公司商讨首轮重大监管", "title_en": "White House to meet with top AI companies ahead of first big regulation push", "summary": "白宫计划与顶级人工智能公司会面，为首轮大规模AI监管措施做准备，会议预计讨论AI模型潜在危害、安全标准和行业自律等问题，标志美国AI治理迈出重要一步。", "source": "CNN", "category": "AI科技", "keywords": "AI监管,白宫,科技政策,人工智能", "url": "https://edition.cnn.com/2026/08/03/tech/white-house-meet-with-top-ai-companies-big-regulation-push", "priority_score": 90, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "US military asks troops for 'creative and unconventional' ideas to punish Iran 美军征求“创造性非常规”对伊打击方案", "title_en": "US military asks troops for 'creative and unconventional' ideas to punish Iran", "summary": "美国军方独家请求军队提出创造性和非常规的创意来惩罚伊朗，显示美伊冲突仍在持续升级。", "source": "CNN", "category": "地缘政治", "keywords": "美军,伊朗,军事打击,冲突升级", "url": "https://edition.cnn.com/2026/08/03/politics/us-military-iran-war-troops-punish", "priority_score": 82, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "'They are murder victims': Senator suggests US strikes have killed people who weren't involved in drug trafficking 参议员凯恩：美军打击或误杀非贩毒关联人员", "title_en": "'They are murder victims': Senator suggests US strikes have killed people who weren't involved in drug trafficking", "summary": "参议员蒂姆·凯恩表示，美国在打击毒品贩运的军事行动中可能误杀了无辜人员，称这些人是谋杀受害者，引发对行动人道主义后果的质疑。", "source": "CNN", "category": "地缘政治", "keywords": "参议院,美军打击,误杀,人道主义", "url": "https://edition.cnn.com/2026/08/03/politics/tim-kaine-boat-strikes-illegal", "priority_score": 80, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump's mail voting appeal tests Supreme Court's anti-chaos election rule 特朗普邮寄投票上诉考验最高法院选举规则", "title_en": "Trump's mail voting appeal tests Supreme Court's anti-chaos election rule", "summary": "特朗普就邮寄投票问题向最高法院提出上诉，考验最高法院的反混乱选举规则，涉及美国国内选举政治与司法争议。", "source": "CNN", "category": "美国政治", "keywords": "特朗普,邮寄投票,最高法院,选举", "url": "https://edition.cnn.com/2026/08/03/politics/trump-mail-voting-supreme-court-appeal", "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},

# ============ 纽约时报 (7) ============
{"title": "Iran and Oman Hold Talks on Reopening the Strait of Hormuz 伊朗与阿曼就重开霍尔木兹海峡举行会谈", "title_en": "Iran and Oman Hold Talks on Reopening the Strait of Hormuz", "summary": "特朗普在取消周末对伊朗打击威胁时援引谈判进展，伊朗与阿曼就重开霍尔木兹海峡举行会谈，但伊朗表示目前与美国没有谈判。", "source": "纽约时报", "category": "地缘政治", "keywords": "伊朗,阿曼,霍尔木兹海峡,谈判", "url": "https://www.nytimes.com/2026/08/03/world/middleeast/iran-talks-us-oman-strait-hormuz-trump.html", "priority_score": 88, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "For Iran, Trump's Reversal on Escalation Shows Who Has the Upper Hand 分析：特朗普在升级问题上的反复显示谁占上风", "title_en": "For Iran, Trump's Reversal on Escalation Shows Who Has the Upper Hand", "summary": "专家表示，伊朗通过扩大地区战事范围，向特朗普发出关于战争扩大危险的警告，特朗普在升级问题上的反复显示德黑兰占据上风。", "source": "纽约时报", "category": "地缘政治", "keywords": "伊朗,特朗普,升级,中东局势", "url": "https://www.nytimes.com/2026/08/03/world/middleeast/iran-trump-escalation.html", "priority_score": 85, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump Says He Canceled Strikes on Iran, Claiming Progress on Outlines of a Deal 特朗普称取消对伊打击，称协议框架有进展", "title_en": "Trump Says He Canceled Strikes on Iran, Claiming Progress on Outlines of a Deal", "summary": "特朗普多次威胁升级对伊朗战争又突然退让，他声称已取消对伊打击并称协议框架取得进展，沙特阿拉伯表示其领导人曾敦促特朗普不要恢复攻击。", "source": "纽约时报", "category": "地缘政治", "keywords": "特朗普,伊朗,取消打击,协议", "url": "https://www.nytimes.com/2026/08/02/world/middleeast/trump-iran-cancels-attack-deal.html", "priority_score": 90, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Pardoned by Trump, a Former President Faces Justice in Honduras 获特朗普赦免后，洪都拉斯前总统面临司法审判", "title_en": "Pardoned by Trump, a Former President Faces Justice in Honduras", "summary": "洪都拉斯前总统胡安·奥兰多·埃尔南德斯在特朗普赦免推翻了其贩毒判决后，面临欺诈和洗钱指控。", "source": "纽约时报", "category": "地区热点", "keywords": "洪都拉斯,特朗普赦免,贩毒判决,司法", "url": "https://www.nytimes.com/2026/08/03/world/americas/juan-orlando-hernandez-trump-honduras.html", "priority_score": 75, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Myanmar Junta Allows Aung San Suu Kyi Rare Contact With an Outsider 缅甸军政府允许昂山素季罕见接触外界", "title_en": "Myanmar Junta Allows Aung San Suu Kyi Rare Contact With an Outsider", "summary": "现年81岁的被罢黜领导人昂山素季会见了一名红十字国际委员会代表，她长期未公开露面曾引发外界对其健康状况的担忧。", "source": "纽约时报", "category": "地缘政治", "keywords": "昂山素季,缅甸,军政府,红十字会", "url": "https://www.nytimes.com/2026/08/03/world/asia/myanmar-aung-san-suu-kyi-photos-icrc.html", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "U.S. Sends Flight With Deportees to Venezuela for First Time Since Quakes 美国地震后首次向委内瑞拉遣送被驱逐者", "title_en": "U.S. Sends Flight With Deportees to Venezuela for First Time Since Quakes", "summary": "一架载有147名委内瑞拉人的飞机周一抵达该国，这是6月地震中遭驱逐者死亡事件引发批评后，美国首次恢复对委内瑞拉的遣返航班。", "source": "纽约时报", "category": "地区热点", "keywords": "美国,委内瑞拉,遣返,地震", "url": "https://www.nytimes.com/2026/08/03/world/americas/venezuela-us-deportation-flights-resume.html", "priority_score": 72, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Russian Opposition Politician Flees to France 俄反对派政治家逃亡法国", "title_en": "Russian Opposition Politician Flees to France", "summary": "63岁的鲍里斯·纳杰日金出现在一段视频中，站在埃菲尔铁塔前，他说自己活着且自由，但不幸的是还不在俄罗斯。", "source": "纽约时报", "category": "地缘政治", "keywords": "俄罗斯,纳杰日金,反对派,流亡", "url": "https://www.nytimes.com/2026/08/03/world/europe/russian-politician-exile-france.html", "priority_score": 75, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},

# ============ 华尔街日报 (7) ============
{"title": "Iran Says No Talks With the U.S. on Hormuz Strait 伊朗称不会与美国就霍尔木兹海峡谈判", "title_en": "Iran Says No Talks With the U.S. on Hormuz Strait", "summary": "伊朗外交部表示不会与美国就霍尔木兹海峡问题进行谈判，但会继续与阿曼就这一关键水道的交通管理进行讨论，特朗普称德黑兰不可信地口是心非。", "source": "华尔街日报", "category": "地缘政治", "keywords": "伊朗,美国,霍尔木兹海峡,外交", "url": "https://www.wsj.com/world/middle-east/iran-says-no-talks-with-the-u-s-on-hormuz-strait-9863c9f0", "priority_score": 88, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Jordan Is Learning Its U.S. Alliance Has a Price in the Iran War 约旦正为美伊战争中的美约同盟付出代价", "title_en": "Jordan Is Learning Its U.S. Alliance Has a Price in the Iran War", "summary": "由于美国在约旦沙漠基地的军事依赖加深，约旦王国已成为伊朗的攻击目标，文章探讨约旦因其与美结盟在当前伊朗冲突中所付出的代价。", "source": "华尔街日报", "category": "地缘政治", "keywords": "约旦,美国同盟,伊朗,地缘政治", "url": "https://www.wsj.com/world/middle-east/jordan-is-learning-its-u-s-alliance-has-a-price-in-the-iran-war-7ce9fd8b", "priority_score": 80, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Summertime Blues Hit China's Factories 夏季困境冲击中国工厂，北京无意大规模刺激", "title_en": "Summertime Blues Hit China's Factories", "summary": "中国经济动能放缓，但北京方面几乎没有表现出实施大规模刺激措施的意愿，文章聚焦中国工厂在夏季面临的困境及官方政策态度。", "source": "华尔街日报", "category": "经济金融", "keywords": "中国经济,制造业,刺激政策,经济放缓", "url": "https://www.wsj.com/world/china/summertime-blues-hit-chinas-factories-69c507f8", "priority_score": 88, "is_summit_level": False, "column": "中国", "date": "2026-08-04"},
{"title": "Ships Can't Move and Power Plants Shut Down as Drought Saps Europe's Rivers 干旱致欧洲河流断航、电厂停摆", "title_en": "Ships Can't Move and Power Plants Shut Down as Drought Saps Europe's Rivers", "summary": "持续干旱对欧洲河流运输和电力生产造成严重影响，导致船舶无法通行、电厂关闭，对地区本已承压的经济构成新挑战。", "source": "华尔街日报", "category": "经济金融", "keywords": "欧洲,干旱,能源,供应链", "url": "https://www.wsj.com/world/europe/ships-cant-move-and-power-plants-shut-down-as-drought-saps-europes-rivers-8b083c62", "priority_score": 75, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "Red Cross Meeting With Suu Kyi Follows Family's Push for Proof of Life 红十字会与昂山素季会面回应家属“在世证明”诉求", "title_en": "Red Cross Meeting With Suu Kyi Follows Family's Push for Proof of Life", "summary": "在昂山素季家人寻求其生存证明之后，红十字会与其进行了会面，提供证据表明这位前领导人在支持者对其健康状况的担忧中依然健在。", "source": "华尔街日报", "category": "地缘政治", "keywords": "缅甸,昂山素季,红十字会,人权", "url": "https://www.wsj.com/world/asia/red-cross-meets-with-myanmars-suu-kyi-offering-proof-of-life-f0cc5642", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Meet the Rabbi Leading Iran's Thousands of Jews 走进领导伊朗数千犹太人的拉比", "title_en": "Meet the Rabbi Leading Iran's Thousands of Jews", "summary": "文章介绍领导伊朗数千名犹太人的拉比耶胡达·格拉米，他在政治与宗教之间走钢丝，试图维系世界上最古老的犹太社区之一。", "source": "华尔街日报", "category": "社会文化", "keywords": "伊朗,犹太社区,宗教,文化", "url": "https://www.wsj.com/world/middle-east/meet-the-rabbi-leading-irans-thousands-of-jews-2704a79e", "priority_score": 65, "is_summit_level": False, "column": "其他", "date": "2026-08-04"},
{"title": "Spain Regains Control of Enclave After Migrants Overrun It 西班牙重夺遭移民涌入的北非飞地控制权", "title_en": "Spain Regains Control of Enclave After Migrants Overrun It", "summary": "在成千上万移民涌入之后，西班牙重新控制了其在北非的飞地，报道关注这一边境危机事件的后续处理与局势恢复。", "source": "华尔街日报", "category": "欧洲", "keywords": "西班牙,移民,边境危机,飞地", "url": "https://www.wsj.com/world/europe/spain-rushes-to-control-border-after-tens-of-thousands-of-migrants-flood-into-exclave-0a6382d0", "priority_score": 75, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},

# ============ 半岛电视台 (8) ============
{"title": "Trump administration sued by 25 states over new tariffs on trading partners 25州起诉特朗普政府贸易伙伴新关税", "title_en": "Trump administration sued by 25 states over new tariffs on trading partners", "summary": "25个州起诉特朗普政府新的贸易伙伴关税，称新关税是重新实施最高法院已裁定非法的关税的借口。", "source": "半岛电视台", "category": "经贸制裁", "keywords": "特朗普,关税,诉讼,最高法院", "url": "https://www.aljazeera.com/news/2026/8/4/trump-administration-sued-by-25-states-over-new-tariffs-on-trading-partners", "priority_score": 92, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Trump warns Iran of 'last chance' for a deal; Israel kills 2 in Gaza 特朗普警告伊朗“最后机会”；以色列在加沙打死2人", "title_en": "Trump warns Iran of 'last chance' for a deal; Israel kills 2 in Gaza", "summary": "特朗普警告伊朗达成协议的机会是最后一次机会，伊朗否认与美国进行谈判；与此同时以色列在加沙的军事行动再致2人死亡，中东局势持续紧张。", "source": "半岛电视台", "category": "地缘政治", "keywords": "特朗普,伊朗,最后机会,加沙", "url": "https://www.aljazeera.com/news/liveblog/2026/8/4/iran-war-live-tehran-denies-us-talks-as-trump-warns-of-last-chance", "priority_score": 88, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Death toll from Venezuela earthquakes passes 6,000 委内瑞拉地震死亡人数突破6000", "title_en": "Death toll from Venezuela earthquakes passes 6,000", "summary": "委内瑞拉地震造成的死亡人数已超过6000人，此前连续强震对该国沿海地区造成毁灭性破坏，重建工作仍在进行。", "source": "半岛电视台", "category": "地区热点", "keywords": "委内瑞拉,地震,伤亡,人道主义", "url": "https://www.aljazeera.com/news/2026/8/3/death-toll-from-venezuela-earthquakes-passes-6000", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Petrol prices strain US households as oil giants Chevron, Exxon profits soar 美国汽油价格挤压家庭，雪佛龙埃克森利润飙升", "title_en": "Petrol prices strain US households as oil giants Chevron, Exxon profits soar", "summary": "在美国汽油价格持续挤压普通家庭预算的同时，石油巨头雪佛龙和埃克森美孚利润大幅攀升，能源价格与通胀压力成为中期选举前的政治焦点。", "source": "半岛电视台", "category": "经济金融", "keywords": "汽油价格,石油巨头,通胀,美国经济", "url": "https://www.aljazeera.com/economy/2026/8/3/petrol-prices-strain-us-households-as-oil-giants-chevron-exxon-profits-soar", "priority_score": 72, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Trump says ongoing talks are Iran's 'last chance' 特朗普称正在进行谈判是伊朗“最后机会”", "title_en": "Trump says ongoing talks are Iran's 'last chance'", "summary": "特朗普要求伊朗彻底投降，霍尔木兹海峡海上封锁不断升级。他强调正在进行的谈判是伊朗的最后机会。", "source": "半岛电视台", "category": "地缘政治", "keywords": "特朗普,伊朗,霍尔木兹海峡,封锁", "url": "https://www.aljazeera.com/news/2026/8/3/trump-blasts-duplicitous-iran-after-tehran-denies-it-is-in-talks-with-the-us", "priority_score": 88, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Uncertainty on Iranians' minds as Trump fluctuates on war and talk 特朗普战和反复令伊朗民众不安", "title_en": "Uncertainty on Iranians' minds as Trump fluctuates on war and talk", "summary": "随着特朗普在冲突与谈判之间反复摇摆，伊朗民众在战争阴云下感到巨大压力，社会情绪持续紧张。", "source": "半岛电视台", "category": "地缘政治", "keywords": "伊朗,民众,战争焦虑,特朗普", "url": "https://www.aljazeera.com/news/2026/8/3/uncertainty-on-iranians-minds-as-trump-fluctuates-on-war-and-talk", "priority_score": 75, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Iraqi Kurdish regional leader meets Syrian president in Damascus 库尔德地区领导人访问大马士革会晤叙利亚总统", "title_en": "Iraqi Kurdish regional leader meets Syrian president in Damascus", "summary": "伊拉克库尔德地区领导人巴尔扎尼在大马士革会晤叙利亚总统沙拉，讨论后阿萨德时代叙利亚的SDF整合与库尔德人权利问题。", "source": "半岛电视台", "category": "地缘政治", "keywords": "库尔德,叙利亚,巴尔扎尼,中东", "url": "https://www.aljazeera.com/news/2026/8/3/iraqi-kurdish-regional-leader-meets-syrian-president-in-damascus", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Pentagon boosts Patriot, THAAD interceptor output amid stockpile strain 五角大楼加速爱国者与THAAD拦截器产能", "title_en": "Pentagon boosts Patriot, THAAD interceptor output amid stockpile strain", "summary": "在库存承压背景下，五角大楼加速导弹拦截器生产，洛克希德·马丁和诺斯罗普·格鲁曼获得数十亿美元合同，扩大爱国者和THAAD系统部件产能。", "source": "半岛电视台", "category": "军事安全", "keywords": "五角大楼,爱国者,THAAD,导弹防御", "url": "https://www.aljazeera.com/economy/2026/8/3/pentagon-boosts-patriot-thaad-interceptor-output-amid-stockpile-strain", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},

# ============ Politico (8) ============
{"title": "Trump has been able to keep oil prices low. But that power may not last forever. 特朗普压低油价的能力或难持久", "title_en": "Trump has been able to keep oil prices low. But that power may not last forever.", "summary": "特朗普通过施压OPEC和威胁制裁等方式维持低油价，但这种能力可能正在减弱。随着共和党进入中期选举冲刺，油价上涨可能成为重大政治风险。", "source": "Politico", "category": "经济金融", "keywords": "油价,中期选举,特朗普,能源政策", "url": "https://www.politico.com/news/2026/08/03/trump-gas-oil-prices-iran-01022998", "priority_score": 78, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "White House finalizes artificial intelligence oversight framework 白宫敲定人工智能监管框架（自愿性质）", "title_en": "White House finalizes artificial intelligence oversight framework", "summary": "白宫最终确定了一项针对人工智能的监管框架，目前为自愿性质，标志着美国政府在AI治理方面迈出关键一步，但自愿性质可能引发效力争议。", "source": "Politico", "category": "AI科技", "keywords": "AI,白宫,监管,科技政策", "url": "https://www.politico.com/news/2026/08/03/white-house-finalizes-voluntary-ai-oversight-framework-01022437", "priority_score": 90, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Senate easily advances stopgap funding deal past first hurdle 参议院通过临时拨款法案首轮程序投票", "title_en": "Senate easily advances stopgap funding deal past first hurdle", "summary": "参议院一项临时拨款法案轻松通过首个程序性投票，避免政府关门，但与众议院版本存在分歧，预计秋季将就预算问题展开激烈对抗。", "source": "Politico", "category": "美国政治", "keywords": "参议院,政府拨款,预算,国会", "url": "https://www.politico.com/live-updates/2026/08/03/congress/senate-cr-vote-01023190", "priority_score": 72, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Democratic-led states sue to block Trump's latest wave of tariffs 民主党州起诉阻止特朗普最新关税浪潮", "title_en": "Democratic-led states sue to block Trump's latest wave of tariffs", "summary": "多个由民主党领导的州联合提起诉讼，试图阻止特朗普政府最新一轮关税政策，贸易政策的法律斗争进一步升级。", "source": "Politico", "category": "经贸制裁", "keywords": "关税,贸易,诉讼,民主党", "url": "https://www.politico.com/news/2026/08/03/democratic-states-trump-tariffs-01023161", "priority_score": 90, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Trump keeps escalating his trade threats. This time, Europe isn't biting. 特朗普升级对欧贸易威胁，欧洲这次不为所动", "title_en": "Trump keeps escalating his trade threats. This time, Europe isn't biting.", "summary": "尽管特朗普继续升级对欧洲的贸易威胁，但欧洲方面此次并未激烈回应，而是采取更冷静克制的态度，显示跨大西洋贸易关系动态正在转变。", "source": "Politico", "category": "经贸制裁", "keywords": "贸易,欧洲,特朗普,关税", "url": "https://www.politico.com/news/2026/08/02/trump-trade-threats-europe-01020492", "priority_score": 85, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "'They feel emboldened': Iran leaving Trump with no good way out 分析：伊朗感到底气十足，特朗普难有良策", "title_en": "'They feel emboldened': Iran leaving Trump with no good way out", "summary": "分析指出，伊朗在谈判中提出强硬要求，使特朗普在伊朗问题上几乎没有好的选择，美国在外交和军事上的选项都复杂且充满风险。", "source": "Politico", "category": "地缘政治", "keywords": "伊朗,外交政策,特朗普,中东", "url": "https://www.politico.com/news/2026/08/02/irans-demands-leave-trump-few-good-options-01020961", "priority_score": 82, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "House Energy and Commerce seeks input on FTC overhaul 众议院能源商务委员会就FTC改革征求意见", "title_en": "House Energy and Commerce seeks input on FTC overhaul", "summary": "众议院能源与商务委员会就联邦贸易委员会（FTC）改革征求公众意见，可能预示美国反垄断执法和消费者保护政策将迎来重大调整，尤其涉及科技行业监管。", "source": "Politico", "category": "AI科技", "keywords": "FTC,国会,反垄断,科技监管", "url": "https://www.politico.com/news/2026/08/03/house-energy-and-commerce-seeks-input-on-ftc-overhaul-01023078", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "European Union ministers to back Spain as Ceuta crisis pushes migration up agenda 欧盟部长支持西班牙应对休达危机", "title_en": "European Union ministers to back Spain as Ceuta crisis pushes migration up agenda", "summary": "随着休达边境危机将移民问题推上议程，欧盟各国部长将表态支持西班牙，凸显欧洲在应对非法移民问题上的内部压力和协调挑战。", "source": "Politico", "category": "欧洲", "keywords": "欧盟,西班牙,移民,休达", "url": "https://www.politico.eu/article/eu-ministers-spain-morocco-ceuta-crisis-pushes-migration-up-the-agenda/", "priority_score": 72, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},

# ============ 华盛顿邮报 (5) ============
{"title": "Iran rejects Trump's claim that talks will restart, adding to weekend of whiplash 伊朗否认特朗普“谈判将重启”说法", "title_en": "Iran rejects Trump's claim that talks will restart, adding to weekend of whiplash", "summary": "特朗普周日晚称已取消自二战以来最大规模的攻击以便恢复谈判，但伊朗周一表示没有计划谈判，美伊关系经历戏剧性反复。", "source": "华盛顿邮报", "category": "地缘政治", "keywords": "伊朗,特朗普,谈判,美伊危机", "url": "https://www.washingtonpost.com/world/2026/08/02/trump-cancels-iran-attack-citing-progress-deal-tehran-israel-alert/", "priority_score": 88, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Labour overtakes Trump-aligned Reform UK in national polls 工党全国民调反超特朗普盟友改革党", "title_en": "Labour overtakes Trump-aligned Reform UK in national polls", "summary": "最新民调显示，英国工党在全国民调中反超与特朗普结盟的改革党，英国政局出现新的变化。", "source": "华盛顿邮报", "category": "欧洲", "keywords": "英国,工党,改革党,民调", "url": "https://www.washingtonpost.com/world/2026/08/03/labour-overtakes-reform-uk-national-polls/", "priority_score": 75, "is_summit_level": False, "column": "欧洲", "date": "2026-08-04"},
{"title": "Boris Nadezhdin, anti-war candidate in Russia, flees to France 俄反战候选人纳杰日金逃往法国", "title_en": "Boris Nadezhdin, anti-war candidate in Russia, flees to France", "summary": "俄罗斯反战总统候选人鲍里斯·纳杰日金逃往法国，此前他曾被指定为外国代理人，其在埃菲尔铁塔前的视频引发关注。", "source": "华盛顿邮报", "category": "地缘政治", "keywords": "俄罗斯,纳杰日金,反战,流亡", "url": "https://www.washingtonpost.com/world/2026/08/03/boris-nadezhdin-anti-war-candidate-russia-flees-france/", "priority_score": 78, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Loomer's Ukraine reversal deepens split in Trump's 'America First' movement 卢默转变立场加深特朗普“美国优先”阵营分裂", "title_en": "Loomer's Ukraine reversal deepens split in Trump's 'America First' movement", "summary": "有影响力的MAGA博主、前基辅批评者劳拉·卢默预计将访问总统，倡导美乌联盟，她的立场转变加深了特朗普美国优先阵营的分裂。", "source": "华盛顿邮报", "category": "美国政治", "keywords": "卢默,乌克兰,特朗普,美国优先", "url": "https://www.washingtonpost.com/politics/2026/08/02/inside-laura-loomer-surprising-turn-ukraine/", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "After months on the Iran war's sidelines, Yemen's Houthis open a dangerous new front 胡塞武装开辟危险新战线，封锁沙特船只", "title_en": "After months on the Iran war's sidelines, Yemen's Houthis open a dangerous new front", "summary": "伊朗支持下的胡塞武装对沙特船只实施封锁，为地区安全担忧再添一条关键水道，中东冲突范围进一步扩大。", "source": "华盛顿邮报", "category": "地缘政治", "keywords": "胡塞武装,沙特,红海,中东冲突", "url": "https://www.washingtonpost.com/world/2026/08/02/strikes-against-saudi-arabia-by-yemens-houthis-widen-dangers-iran-war/", "priority_score": 82, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},

# ============ 美联社 (7) ============
{"title": "New talks are 'last chance' for Iran to forge a deal and avoid escalation of US strikes, Trump says 特朗普：新谈判是伊朗达成协议避免升级的“最后机会”", "title_en": "New talks are 'last chance' for Iran to forge a deal and avoid escalation of US strikes, Trump says", "summary": "特朗普称与伊朗的新一轮谈判是达成协议、避免美国进一步军事打击的最后机会，美伊外交施压与潜在军事升级处于最紧迫关头。", "source": "美联社", "category": "地缘政治", "keywords": "伊朗,美国打击,外交,最后机会", "url": "https://apnews.com/article/trump-iran-war-gulf-allies-fb81a68f999f4a7b0498ae71cbffe8e5", "priority_score": 90, "is_summit_level": True, "column": "地区热点", "date": "2026-08-04"},
{"title": "Trump optimistic Iran talks will reopen strait, and other developments in the Middle East 特朗普乐观预期伊朗谈判重开海峡", "title_en": "Trump optimistic Iran talks will reopen strait, and other developments in the Middle East", "summary": "特朗普对伊朗谈判持乐观态度，认为有望重新开放霍尔木兹海峡，报道汇总了中东地区其他最新进展，直接关系全球能源运输通道和地区安全格局。", "source": "美联社", "category": "地缘政治", "keywords": "伊朗,霍尔木兹海峡,中东,谈判", "url": "https://apnews.com/article/mideast-iran-us-israel-palestinians-gaza-3b92568b6f2eec283eb51d0327ee682a", "priority_score": 85, "is_summit_level": False, "column": "地区热点", "date": "2026-08-04"},
{"title": "Elon Musk's xAI sues Minnesota over its first-in-the-nation law banning 'nudification' technology 马斯克xAI起诉明尼苏达州AI“脱衣”技术禁令", "title_en": "Elon Musk's xAI sues Minnesota over its first-in-the-nation law banning 'nudification' technology", "summary": "马斯克的xAI公司起诉明尼苏达州，因其通过全美首部禁止脱衣换装AI技术的法律，这是科技巨头与州政府围绕AI监管的重大法律冲突。", "source": "美联社", "category": "AI科技", "keywords": "AI监管,xAI,马斯克,deepfake", "url": "https://apnews.com/article/minnesota-artificial-intelligence-nudification-x-elon-musk-deepfake-131184be939d540de093b567b12c9e16", "priority_score": 82, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Jury finds Instagram and YouTube liable in a landmark social media addiction trial 陪审团裁定Instagram与YouTube对社交媒体成瘾负责", "title_en": "Jury finds Instagram and YouTube liable in a landmark social media addiction trial", "summary": "陪审团在一场具有里程碑意义的诉讼中裁定Instagram和YouTube对社交媒体成瘾负有责任，该裁决可能对全球科技平台的商业模式和责任标准产生深远影响。", "source": "美联社", "category": "AI科技", "keywords": "社交媒体,成瘾,Instagram,YouTube", "url": "https://apnews.com/article/social-media-addiction-trial-la-5e54075023d837ccdc76c4ca512e925d", "priority_score": 80, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "Trump accounts were closed in 2021 due to concerns over possible money laundering, Capital One says 第一资本称2021年因洗钱担忧关闭特朗普账户", "title_en": "Trump accounts were closed in 2021 due to concerns over possible money laundering, Capital One says", "summary": "第一资本银行表示，出于对可能涉及洗钱的担忧，于2021年关闭了特朗普的账户，涉及金融监管、政治人物与银行业关系。", "source": "美联社", "category": "美国政治", "keywords": "特朗普,第一资本,洗钱,银行业", "url": "https://apnews.com/article/trump-capital-one-debanking-money-laundering-5f5cc717e1e011e6195bd765c8f90bad", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
{"title": "US dollar weakens sharply against the Japanese yen after market interventions 美日干预后美元兑日元大幅走弱", "title_en": "US dollar weakens sharply against the Japanese yen after market interventions", "summary": "在美日政府市场干预后，美元兑日元大幅走弱，涉及汇率干预、国际贸易与金融市场的联动，对全球经济和贸易政策有直接影响。", "source": "美联社", "category": "经济金融", "keywords": "美元,日元,汇率干预,市场", "url": "https://apnews.com/article/yen-dollar-currency-trump-economy-7316599afed35629a27ae23a35f569fd", "priority_score": 80, "is_summit_level": False, "column": "经济金融", "date": "2026-08-04"},
{"title": "US stocks rally near a record as falling oil prices ease Wall Street's worries about inflation 油价回落缓解通胀担忧，美股逼近历史高位", "title_en": "US stocks rally near a record as falling oil prices ease Wall Street's worries about inflation", "summary": "由于油价下跌缓解了市场对通胀的担忧，美国股市接近历史高点，反映能源价格、通胀预期与资本市场之间的传导关系。", "source": "美联社", "category": "经济金融", "keywords": "美股,油价,通胀,华尔街", "url": "https://apnews.com/article/stocks-markets-dollar-yen-trump-oil-d19a8f9a77b6fceca41da3e4b6bf17aa", "priority_score": 75, "is_summit_level": False, "column": "美国", "date": "2026-08-04"},
]

errs = []
for i, it in enumerate(items):
    if not it.get('url', '').startswith('https://'):
        errs.append((i, it.get('title'), 'URL无效'))
    if not it.get('title'):
        errs.append((i, 'NO_TITLE', '缺标题'))
if errs:
    for e in errs:
        print('ERR:', e)
else:
    with open('data/news-webfetch.json', 'w', encoding='utf-8') as f:
        json.dump(items, f, ensure_ascii=False, indent=2)
    from collections import Counter
    print('OK: %d items, URL 100%% valid' % len(items))
    print('by source:', dict(Counter(x['source'] for x in items)))
    print('by category:', dict(Counter(x['category'] for x in items)))
